### ISSUE TITLE
Convert getMembers to id64?

### ISSUE THREAD

**Issue by dragonbanshee** [DoctorMcKay/node-steamcommunity#1]
Am I able to use the getMembers method to convert the members array to an array of steamid64s?

Currently i'm using this:
```javascript
community.getGroup(groupname, function(err, group) {
    if(err) logger.error(error);
    else {
        group.getMembers(function(err, members) {
            for(var i = 0; i < members.length; i++) {
                var sid = new SteamID(members[i]);
                var _id64 = sid.getSteamID64();
            }
        });
    }
});
```

I get an error at the `var sid = new SteamID(members[i]);`. Am I not able to do this?

**Comment by DoctorMcKay** [comment]
Each item in the `members` array is already a `SteamID`, just call `getSteamID64()` on it directly.

**Comment by dragonbanshee** [comment]
Oh, didn't know that. Thanks.
