### ISSUE TITLE
More information about 2FA

### ISSUE THREAD

**Issue by AKagNA** [DoctorMcKay/node-steamcommunity#100]
I think you have to give more information about 2FA and about how to use. Generally we are asking about this, we are living problems about this. You can do really really really good tutorial about it. Thanks.

**Comment by DoctorMcKay** [comment]
>**Have a question about the module or coding in general? *Do not create a GitHub issue.* GitHub issues are for feature
requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).
Such issues may be ignored!**
