### ISSUE TITLE
Steam Confirmation Problem

### ISSUE THREAD

**Issue by FonyLebeL** [DoctorMcKay/node-steamcommunity#101]
```
SteamCommunity.login({
    "accountName": logOnOptions.account_name,
    "password": logOnOptions.password,
    "twoFactorCode": SteamTotp.getAuthCode('shared_secret')
}, function(err, sessionID, cookies, steamguard, oAuthToken){
    if (err) { log(err); }
        SteamCommunity.setCookies(cookies);
        time = Math.round(Date.now() / 1000);
        key = SteamTotp.getConfirmationKey('identity_secret', time, 'allow');
        SteamCommunity.getConfirmations(time, key, function (err, confirmations) {
            console.dir(err);
            console.dir(confirmations);
            //SteamCommunity.startConfirmationChecker(10000);
            //SteamCommunity.checkConfirmations()
        });
});
```

**I can't do auto allow/cancel my trade offer.
When I use a 'conf' tag of getConfirmationKey - it's working.
When I use a 'allow' or 'cancel' or 'details' tag of getConfirmationKey - it's returns next error**:

[Error: It looks like your Steam Guard Mobile Authenticator is providing incorre
ct Steam Guard codes. This could be caused by an inaccurate clock or bad timezon
e settings on your device. If your time settings are correct, it could be that a
 different device has been set up to provide the Steam Guard codes for your acco
unt, which means the authenticator on this device is no longer valid.]
undefined

**startConfirmationChecker is not working too.**

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

You need "conf" to get confirmations, "details" to get details, and "allow" to accept.
