### ISSUE TITLE
You cant use steamid64 in getSteamUser

### ISSUE THREAD

**Issue by trzyrazyzero** [DoctorMcKay/node-steamcommunity#103]
You cant use steamid64 because its check it is string or not:
https://github.com/DoctorMcKay/node-steamcommunity/blob/aac26212d7c9f6c39797e62e46fef7865fb3fd3f/classes/CSteamUser.js#L16

`community.getSteamUser(76561198300985749, function(err, user) {
		if(err) {
			console.log(err);
		}
		console.log(user);
	});`
SteamID will be: 76561198300985740 so you must pass parameter as string.
I tried to make something like this:
`var sid = new SteamID('76561198006409530');
if(!sid.isValid()) {
throw new Error("id parameter should be a user URL string or a SteamID object");
}`
But if you enter other value in SteamID object it will throw error.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

    community.getSteamUser(new SteamID('76561198300985749'), function(err, user) {
        // do stuff
    });
