### ISSUE TITLE
emit "onError" for chatLogon when error occurs

### ISSUE THREAD

**Issue by albertliang** [DoctorMcKay/node-steamcommunity#104]
If chatLogon fails for whatever reason, I'm currently waiting on the 'debug' event to see if the ChatState = LogOnFailed. But because it's set AFTER the 'debug' emit, I'm waiting 2 timeouts to get the LogOnFailed state and the message doesn't match the state by then.

Can you change the 'debug' emit to 'onError' and move the:
self.chatState = SteamCommunity.ChatState.LogOnFailed;
line to BEFORE the emit?
Thanks!

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/Steam-Chat#chatlogonfailed
