### ISSUE TITLE
STEAM.RIP

### ISSUE THREAD

**Issue by Foltos2016** [DoctorMcKay/node-steamcommunity#107]
i use steam.rip api. and lots of time see steam.rip site write STEAM RIP
(but steam not rip) only problem very lot of time get web inventory status (on USA)
You can fix it? (sorry me english is bad)
 
Pitcure: http://s33.postimg.o...6n/STEAMRIP.png

(SAME opened dev.doctormckay.com but not answer me)

https://dev.doctormckay.com/topic/362-steamrip-api-problem/

**Comment by DoctorMcKay** [comment]
Last I checked, this isn't a steam.rip issue tracker.

**Comment by Foltos2016** [comment]
But man every day write steam.rip (and see too many request) lots of time.

now: Web Inventories	OK	9 mins (but if you check later) then again too many request.....

and another country web inventories its good

Web Inventories	OK	22 hrs (TX USA)
Web Inventories	OK	21 hrs (NJ USA)
Web Inventories	OK	20 hrs (WA USA)

ALWAYS PROBLEM  GA USA 
now: Web Inventories	OK	9 mins

and later again steam rip and (too many requests)

**Comment by Foltos2016** [comment]
Again: https://s31.postimg.org/mwa0usku3/AGAINSR.png

Drmckay why not fix?
