### ISSUE TITLE
Crash due to Illegal Access in getSessionID routine

### ISSUE THREAD

**Issue by kinsi55** [DoctorMcKay/node-steamcommunity#11]
An App of mine crashed a couple weeks ago while testing, this was the second time (in months) this happened.

```
.....node_modules/steamcommunity/index.js:137
    return decodeURIComponent(match[2]);
```

i reckon this would be hard to reproduce, or even fix, just wanted to report it :)

**Comment by DoctorMcKay** [comment]
Do you have the full error message and/or stack trace?

**Comment by kinsi55** [comment]
Unfortunantely thats all the info that was logged before the crash.
