### ISSUE TITLE
Force logout/disconnect

### ISSUE THREAD

**Issue by OrahKokos** [DoctorMcKay/node-steamcommunity#110]
Hello, 
I'm having trouble finding a way to force disconnect after a successful login.
Is there such a feature, I did not find anything in the wiki.
Thanks.

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

This module doesn't `connect` or `disconnect` to Steam network, if you want to log in as different user, just use `login()` or `setCookies()` again.
