### ISSUE TITLE
Error CAPTHA

### ISSUE THREAD

**Issue by latinopl** [DoctorMcKay/node-steamcommunity#111]
What is going on? Can some help mi with this issue?
[http://scr.hu/2cv2/qpavx
](url)

This is not working:
[https://github.com/DoctorMcKay/node-steamcommunity/commit/1c3817b797ada7f73fb9ad0e6ca076d5ad6075e9](url)

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

You need to provide a CAPTCHA solution to log on.
