### ISSUE TITLE
marketSearch method

### ISSUE THREAD

**Issue by bduman** [DoctorMcKay/node-steamcommunity#112]
When i use this `marketSearch` method with express framework. It returns to me "self.request is not a function" error. I do a little debugging operation. I switched in \steamcommunity\classes\CMarketSearchResult.js, 38. lines code from `request` to `this.httpRequest`. Then it works and returns possiblity values. Thanks for repo.. :)

**Comment by DoctorMcKay** [comment]
Thanks for the report. This should be fixed in v3.21.0.
