### ISSUE TITLE
marketSearch method steam results

### ISSUE THREAD

**Issue by bduman** [DoctorMcKay/node-steamcommunity#113]
![screenshot_1](https://cloud.githubusercontent.com/assets/5374623/16399916/55696c80-3cdf-11e6-9b6c-c9b56a36d3c8.png)

When i search on steam app. Results come with query string.

**Comment by DoctorMcKay** [comment]
Fixed in [v3.21.2](https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.21.2), thanks for the report.
