### ISSUE TITLE
[HELP] Mobile confirmation timezone error!

### ISSUE THREAD

**Issue by budysvk** [DoctorMcKay/node-steamcommunity#114]
Hello. Im using node-steamcommunity to accept trades but i've got an error:

> Error: It looks like there is a problem with the time or timezone settings on your device. You will not be able to act on any confirmations until that problem is resolved.

Identity secret is from WinAuth , shared secret too and it is working
In WinAuth i can still confirm trades but bot cant.

I tried everything, time offset , identity_secret is right , i cant figure out why i am getting this error.
I decided to go there for your advice , 

Thank you so much

**Comment by budysvk** [comment]
I had this problem with shared secret too, i had to do offset, but with identity secret it isnt working

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

You need to either set your clock to be correct (preferable), or use your offset when getting the time for a confirmation key.

**Comment by budysvk** [comment]
This is my code for confirmation, how can i put offset here? I tried put like shared_secret but it isnt working:

> community.on('newConfirmation', function(confirmation) {
	var time = Math.floor(Date.now() / 1000);
	confirmation.respond(time, SteamTotp.getConfirmationKey(account.identity_secret, time, "allow"), true, function(err){
		if(err)
		{
			console.log(err);
		}
	});
});
community.on('confKeyNeeded', function(tag, callback) {
    var time = Math.floor(Date.now() / 1000);
    callback(null, time, SteamTotp.getConfirmationKey(account.identity_secret, time, tag));
    console.log('Checking for confirmation....');
});

**Comment by DoctorMcKay** [comment]
```js
community.on('newConfirmation', function(confirmation) {
    var time = SteamTotp.time(offset);
    confirmation.respond(time, SteamTotp.getConfirmationKey(account.identity_secret, time, "allow"), true, function(err){
        if(err)
        {
            console.log(err);
        }
    });
});
community.on('confKeyNeeded', function(tag, callback) {
    var time = SteamTotp.time(offset);
    callback(null, time, SteamTotp.getConfirmationKey(account.identity_secret, time, tag));
    console.log('Checking for confirmation....');
});
```

**Comment by budysvk** [comment]
Error: Offset is not defined

**Comment by DoctorMcKay** [comment]
You have to actually get your offset.

**Comment by budysvk** [comment]
like this?

> SteamTotp.getTimeOffset(function(err, offset, latency)

**Comment by DoctorMcKay** [comment]
Yes.

**Comment by budysvk** [comment]
Thank you so much! Sharing the solution to you guys! 

> community.on('newConfirmation', function(confirmation) {
	SteamTotp.getTimeOffset(function(err, offset, latency) {
    var time = SteamTotp.time(offset);
    confirmation.respond(time, SteamTotp.getConfirmationKey(account.identity_secret, time, "allow"), true, function(err){
        if(err)
        {
            console.log(err);
        }
    });
    });
});
community.on('confKeyNeeded', function(tag, callback) {
	SteamTotp.getTimeOffset(function(err, offset, latency) {
    var time = SteamTotp.time(offset);
    callback(null, time, SteamTotp.getConfirmationKey(account.identity_secret, time, tag));
    console.log('Checking for confirmation....');
    });
});

**Comment by scholtzm** [comment]
Setting your clock would be a lot more efficient though.
