### ISSUE TITLE
Cannot login with steamcommunity node?

### ISSUE THREAD

**Issue by Savikas** [DoctorMcKay/node-steamcommunity#115]
Hey,

I'm trying to login to steam, but I keep getting an error "Error: SteamGuardMobile". My time is right, I live in Estonia.

```js
SteamTotp.getTimeOffset(function(err, offset, latency) {
    account.twoFactorCode = SteamTotp.generateAuthCode(account.shared_secret, offset); 
    account.auth = false;
    logger.debug(account);
    community.login(account, login);
});
```

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

Either your secret is wrong or you're trying to reuse a code.
