### ISSUE TITLE
Steam update - new confirmation

### ISSUE THREAD

**Issue by trzyrazyzero** [DoctorMcKay/node-steamcommunity#118]
Now module accept each confirmations, but after steam update they add accepting all pending confirmations and i think this module should use it.

**Comment by Xetrics** [comment]
+1

**Comment by DoctorMcKay** [comment]
I am aware of this capability. I need to test it still with trades, as the official app doesn't show checkboxes for trade offer confirmations.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.23.0
