### ISSUE TITLE
getSteamUser returns incorrect values for vacBanned and isLimitedAccount

### ISSUE THREAD

**Issue by s992** [DoctorMcKay/node-steamcommunity#12]
Testing against my [own profile](http://steamcommunity.com/id/seaNw_?xml=1), `getSteamUser` returns the following incorrect values for `vacBanned` and `isLimitedAccount`:

```js
{
  vacBanned: true,
  isLimitedAccount: true
}
```

Looks like it's caused by attempting to cast a string "0" to a boolean in the `CSteamUser` constructor:

```js
this.vacBanned = !!processItem('vacBanned', false);
this.isLimitedAccount = !!processItem('isLimitedAccount');
```

I can put together a pull request for this tomorrow or Friday, if you want one.

**Comment by DoctorMcKay** [comment]
Fixed in v3.10.0, thanks.
