### ISSUE TITLE
Steam Market

### ISSUE THREAD

**Issue by Max0nyM** [DoctorMcKay/node-steamcommunity#120]
Can we buy from market with this ?

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

**Comment by DoctorMcKay** [comment]
The answer is no.
