### ISSUE TITLE
Publickey bug

### ISSUE THREAD

**Issue by darkwar123** [DoctorMcKay/node-steamcommunity#124]
bash-0 (err): /node_modules/steamcommunity/index.js:83
bash-0 (err):           if(!body.publickey_mod || !body.publickey_exp) {
bash-0 (err):                   ^
bash-0 (err): TypeError: Cannot read property 'publickey_mod' of undefined
bash-0 (err):     at SteamCommunity.<anonymous> (/node_mod                                                     ules/steamcommunity/index.js:83:11)

**Comment by DoctorMcKay** [comment]
Are you up to date?
