### ISSUE TITLE
Inventory history paging has changed

### ISSUE THREAD

**Issue by DoctorMcKay** [DoctorMcKay/node-steamcommunity#126]
Instead of a `p` parameter for the page number, Steam now requires `after_time` and `after_trade` parameters (`after_trade` is optional apparently) in order to page through the entries.

**Comment by meitinglei** [comment]
Does anybody fix it, thank you very much!

**Comment by Lagg** [comment]
Since more calamity has ensued with regards to this page after today's update (namely that it's captcha'd now). There should probably be some discussion on how severe it is and if receipts actually work reasonably again without being empty.

**Comment by Lagg** [comment]
Per the forum post it looks like this is indeed an SIH abuse countermeasure. I'm still unable to determine what the rate limit actually is.

**Comment by DoctorMcKay** [comment]
Inventory history gets captcha'd too? I was only aware of the trade offers page having it.

Anyway, this now works in v3.24.0. Usage has changed a bit and might be a tad confusing. Please direct questions to [this thread](https://dev.doctormckay.com/topic/536-psa-if-you-use-getinventoryhistory-this-is-what-changed).

**Comment by Lagg** [comment]
To be honest I'm not sure anymore. At first it seemed like it based on reports but I may be mistaken. It would certainly be nice if the scope was limited. I hope so.

**Comment by DoctorMcKay** [comment]
I refreshed both the trade offers and inventory history pages overnight, and only the trade offers page got captcha'd.

**Comment by Lagg** [comment]
Awesome, that explains why I couldn't reproduce it. Thanks for taking the time to do a thorough reproduction attempt.
