### ISSUE TITLE
Steam ask captcha on tradeoffers page FROM TODAY

### ISSUE THREAD

**Issue by tuktun** [DoctorMcKay/node-steamcommunity#127]
From today sometimes on different accounts Steam ask **captcha** on **trade offers page**.
[**Screenshot**](http://imgur.com/a/6peSV)
Can you add API to catch this captcha and answer to Steam?
Thanks.

P.S. I added this to _Issues_ because it is important feauture for correct and stable work of applications.

**Comment by DoctorMcKay** [comment]
steamcommunity doesn't request the trade offers page. If you are, you're clearly doing it wrong and as a result Valve added that CAPTCHA to stop you.
