### ISSUE TITLE
mobile authentication - really slow

### ISSUE THREAD

**Issue by Tutyko2016** [DoctorMcKay/node-steamcommunity#129]
**Since today the bot is confirming the mobile authentication really slow, is there any solution ?**

**Comment by Tutyko2016** [comment]
**since today the mobile authentication is a lot slower than it was before, is there any solution ?**

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**
