### ISSUE TITLE
The command prompt window on backpack.tf automatic keeps asking for captcha?

### ISSUE THREAD

**Issue by V1V3** [DoctorMcKay/node-steamcommunity#132]
[http://imgur.com/a/zqOl0](url) < This is an image of my screen right now.
Basically it keeps asking for captcha even though I'm pretty sure I enter it right. Everything else, my username and invisible password, are correct. It's just that the captcha doesn't even let me get anything done as things currently stand, and I was browsing forums where I stumbled upon a post that said I should post my problem here.

**Comment by DoctorMcKay** [comment]
backpack.tf is probably using an older version from before when this was changed.
