### ISSUE TITLE
sent item confirm trade

### ISSUE THREAD

**Issue by waza123x** [DoctorMcKay/node-steamcommunity#135]
When I sent item to other user, i need to confirm it on mobile app, I run

`community.startConfirmationChecker(25000, config.identitySecret); `

but it do not confirm my trade.. whats wrong ?

**Comment by DoctorMcKay** [comment]
Add `community.on('debug', console.log);` and see what error you're getting.

**Comment by waza123x** [comment]
щл

**Comment by waza123x** [comment]
info: [10/29/2016 6:55:12 PM] community debug: Checking confirmations
info: [10/29/2016 6:55:15 PM] Trade confirmed


nevermind, works fine.
