### ISSUE TITLE
How i can get normal SteamID from Object?

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steamcommunity#136]
I want to get the normal SteamID from chatMessage

```
community.on('chatMessage', function(sender, text) {
	console.log(sender);
	console.log(text);
});
```

"sender" is like 
`SteamID { universe: 1, type: 1, instance: 1, accountid: 12312331 }`

How i can get the normal steamid? Like 1257182751278 
I dont find anything

**Comment by scholtzm** [comment]
It's the first thing in the docs, seriously: https://github.com/DoctorMcKay/node-steamcommunity/wiki#steamid

**Comment by Marow** [comment]
Oh my god... sry... thanks :)

**Comment by Aareksio** [comment]
Psss...

**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**
