### ISSUE TITLE
inviteToGroup not found and inviteUserToGroup Error HTTP 401

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steamcommunity#137]
so my fault

**Comment by good-live** [comment]
What exactly have you done wrong?
Im recieving a HTTP error 400:

`var SteamCommunity = require('steamcommunity');
var SteamID = require('SteamID');
var community = new SteamCommunity();

community.login({
    "accountName": "******",
    "password": "********",
    "authCode": null,
    "twoFactorCode": null,
    "captcha": null
}, function (err, sessionID, cookies, steamguard) {
    if(!err)
        console.log("Sucessfull :)");

    new SteamID("[g:1:571]");
    community.inviteUserToGroup("[U:1:2186242]", new SteamID("[g:1:571]"), function (err) {
        if(err)
            console.log("ERROR: :/ " + err);
    });
})`

Output:
`Sucessfull :)
ERROR: :/ HTTP error 400
`
