### ISSUE TITLE
Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes.

### ISSUE THREAD

**Issue by naksuasd** [DoctorMcKay/node-steamcommunity#138]
Delete please.

**Comment by andrewda** [comment]
Issues cannot be deleted on GitHub. Usually it's best to explain the issue and explain how you fixed it so people who experience the same problem in the future can look at this thread and don't have to open their own issue.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**
