### ISSUE TITLE
Different localAddress for different calls?

### ISSUE THREAD

**Issue by jsieler** [DoctorMcKay/node-steamcommunity#139]
I know that there is a possibility to define localAddress inside a constructor. But is there a possibility to make different calls with different localAddresses? Like getting user profiles with ip A, confirmations with ip B and users inventories with ip C?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

You can use an [HTTP pre-hook](https://github.com/DoctorMcKay/node-steamcommunity/wiki/HTTP-Hooks) for this.

**Comment by jsieler** [comment]
Is there any pre-hook example?
