### ISSUE TITLE
Question by editProfile

### ISSUE THREAD

**Issue by Kasp42** [DoctorMcKay/node-steamcommunity#141]
Question by [editProfile](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#editprofilesettings-callback)
If I want to change just one field eg summary or customURL I need to send all data or only those who want to change?

**Comment by Aareksio** [comment]
> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

**Comment by Kasp42** [comment]
Sorry

**Comment by Aareksio** [comment]
Tested it for you - you don't have to supply all fields.

**Comment by Kasp42** [comment]
I checked and I did.
But when I change my summary is disabled showcase or changing to another
