### ISSUE TITLE
No way to buy or sell market items

### ISSUE THREAD

**Issue by darkf** [DoctorMcKay/node-steamcommunity#144]
You can view the price, but not buy or sell.

**Comment by scholtzm** [comment]
Market automation (selling, buying) is against the ToS.

**Comment by darkf** [comment]
@scholtzm I see, so unimplementable. Thanks!

**Comment by DoctorMcKay** [comment]
Shameless plug: https://opskins.com/kb/api-isales#method-listitems-v1

**Comment by andrewda** [comment]
And https://github.com/OPSkins/node-opskins-api, for that matter.
