### ISSUE TITLE
getUserInventory() 12sec time response

### ISSUE THREAD

**Issue by thohoh** [DoctorMcKay/node-steamcommunity#146]
Hello folks.
I'm getting very slow data response while in the browser response is instant.

**Comment by andrewda** [comment]
Well, you can see the getUserInventory() code [here](https://github.com/DoctorMcKay/node-steamcommunity/blob/e8a43734be863a079d51ea6129c075a7a70312b4/components/users.js#L260-L323). It only makes one request and creates an array of items, so there shouldn't be a huge difference.

Are you sure your internet is not super slow when making the request? Try making the same request in your code to `https://steamcommunity.com/id/YOUR_PROFILE/inventory/json/730/2` and see how long it takes.

**Comment by thohoh** [comment]
@andrewda You're right, the problem with my nodejs, sorry for that. Closed.
