### ISSUE TITLE
Malformed Response when calling enableTwoFactor

### ISSUE THREAD

**Issue by jmeyer2k** [DoctorMcKay/node-steamcommunity#15]
My code logs in without error, but when I call enableTwoFactor, the callback errors out with Error: Malformed response

```javascript
community.login({
  "accountName": params.username,
  "password": params.password,
  "steamguard": params.botSteamId + "||" + params.webSteamAuth
}, function(err, sessionId, cookies, steamguard) {
  community.enableTwoFactor(function(err, response) {
    console.log(err, response);
    fs.writeFile('twofactor.2fa', response);
  })
})
```

**Comment by DoctorMcKay** [comment]
Either your account is limited, or Valve just doesn't like you.

The module must pull an oauth token for the WebAPI from the webchat page. In my experience, Valve randomly locks accounts out of that feature. If you attempt to open https://steamcommunity.com/chat on that account, you will likely get an access denied error.

Submit a Steam support ticket if you want more information about that and your account isn't limited.

**Comment by jmeyer2k** [comment]
Yeah my account was limited. Thanks do much.

**Comment by kenzik** [comment]
Is there any workaround for this issue?

**Comment by DoctorMcKay** [comment]
@kenzik Spending $5 may or may not allow it to work. I have a number of accounts that are not limited but still cannot use it. You can use [node-steam-user](https://github.com/DoctorMcKay/node-steam-user) which should always work.

@jmeyer2k The error will be clarified in the next release.
