### ISSUE TITLE
Request: More steam group functions

### ISSUE THREAD

**Issue by fluxX04** [DoctorMcKay/node-steamcommunity#152]
Hello,

we have some spammers around on our steam group and i would like to punish them automatically by a steam bot who is watching on new comments.

So is there a chance that functions get added for the comments system like we have it on the steamcommunity webpage (list of all new comments, delete a comment, delete and ban author of a comment etc.)?

Greetz

**Comment by Vankxr** [comment]
I agree, I have also noticed some days ago that there is a function to edit and delete events, but there is no function where you can actually get a valid `eventID` to use with those functions like you have `getAllAnnouncements` for announcements

**Comment by Jarzon** [comment]
I'm currently working on open source bot that does that.

**Comment by Jarzon** [comment]
The requested feature have been added in v3.34

**Comment by DoctorMcKay** [comment]
Ah, it was. I forgot to document that or note it in the changelog.
