### ISSUE TITLE
Passing Error message string instead of Error object

### ISSUE THREAD

**Issue by Lagg** [DoctorMcKay/node-steamcommunity#153]
Hi, I'm trying to debug whatever quirks Valve's last set of changes caused. This may be related to it. After experiencing an odd issue where  `Error.message` was undefined I found [this line](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/inventoryhistory.js#L52).

I'm careful about assumptions when it comes to JS typing because naturally. But I assume this was not intended?

**Comment by scholtzm** [comment]
Considering the two lines below, this is definitely a typo.

**Comment by DoctorMcKay** [comment]
That's a mistake, yeah. I'll correct it.

That said, I discourage use of that method. [IEconService/GetTradeHistory](https://lab.xpaw.me/steam_api_documentation.html#IEconService_GetTradeHistory_v1) is far more robust and stable.

**Comment by Lagg** [comment]
Didn't even know such a method was added. Thanks.
