### ISSUE TITLE
Bots returned completely wrong assetid's for item.

### ISSUE THREAD

**Issue by rokshis** [DoctorMcKay/node-steamcommunity#158]
The bots have been operating for a very long time successfully without any problems at all. Just yesterday, a an extremely strange phenomena happened. Yesterday one offer occurred, for which the assigned assetids of the items were incorrect. The assetid's assigned to the item didn't even exist. It wasn't duplicates, and those assetid's never have been in our inventories.  The assetid's are returned with function "getReceivedItemsAsync()" (Using bluebird promises).

Are there any information on this type of issue?

**Comment by DoctorMcKay** [comment]
For starters, you're in the wrong repository. This isn't steam-tradeoffer-manager.

Sounds like your trade might have gotten rolled back. `getReceivedItems` will still work even if the trade didn't fully complete.

Regardless, this is Steam and there's nothing I can do about it.
