### ISSUE TITLE
2 factor finalization issues

### ISSUE THREAD

**Issue by LeCoffee** [DoctorMcKay/node-steamcommunity#16]
Hey!

When trying to finalize 2 factor using this lib, it gives invalid callback, looking at the code in twofactor.js instead of the wiki you actually want the secret + the activation code + the callback not just code and callback.

When you pass all 3 parameters i get the following JSON:
```
{ 
  success: true,
  want_more: true,
  server_time: '1448932846',
  status: 2 
}
```
which I understand from EResult means failure. What more exactly do I need to supply and is the "secret" parameter you ask for the shared_secret or the identity_secret or the secret_1 or the secret parameter in the URI from the enable2factor response.

after the third attempt the code crashes with a response of:

```
{ success: false, server_time: '1448932847', status: 88 }
```

Then it crashes with callback is not a function on line 104

Thanks for all your effort, you've made amazing contributions to both node and steam automation.

edit:
~~Test 1 (using secret_1): { status: 2 }~~
~~Test 2 (identity_secret): { status: 2 }~~
~~Test 3 (uri secret)         : { status: 2 }~~
edit 2:
those tests are invalid the sms code changed?

edit3:
So from what i've determined testing, once you execute finalize it invalidates your old enable data. but when you finalize it steam returns "want_more" twice then the server time changes the 2 fa code generated by totp expires and returns an 88 message which means invalid 2fa code.
edit4:
Just tried it with another completely separate bot with the shared_secret and it seemed to work with want_more set to false so maybe the bot I was testing was disabled in some way but I can't seem to find whats different I set them both up the exact same way... Any ideas?

**Comment by LeCoffee** [comment]
Thank you!

**Comment by LeCoffee** [comment]
Thank you, however this still isn't any use for finding out what exactly more it wanted... Anyways tried it again and seemed to work so for all I know it could've been some kind of cooldown but I've been using the bot for months now so doubt that.

**Comment by DoctorMcKay** [comment]
It was entirely a bug in the library. want_more meant that it wanted the client to send another verification code. The library was supposed to do so automatically, but it was checking response properties in the wrong order.

**Comment by LeCoffee** [comment]
Ah no worrys, thanks for the fix :)
