### ISSUE TITLE
Proxy support for requests

### ISSUE THREAD

**Issue by Rob--** [DoctorMcKay/node-steamcommunity#166]
To prevent getting 429s you could add proxy support for requests that don't require users to be logged in such as getting inventories, getting market prices, etc.

An idea could be a method that you call to set the proxy address when the bot logs in, or to pass it as an optional parameter to functions that could make use of it?

The request library has great support for proxies, just check out the documentation!

**Comment by Aareksio** [comment]
> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

```
const community = new Steamcommunity({ request: request.defaults({ proxy: myProxyURL }) });
// Or shorter
const community = new Steamcommunity({ request: { proxy: myProxyURL } });
```

**Comment by Rob--** [comment]
Oops, definitely should've read the docs, didn't realise you could do this, sorry!
