### ISSUE TITLE
Error: There was an error sending your trade offer. Please try again later. (26)] eresult: 26

### ISSUE THREAD

**Issue by dilipsoni** [DoctorMcKay/node-steamcommunity#167]
I am genrating offer id using bot for one player inventroy its working fine, but when i am using another player inventory its gerating error There was an error sending your trade offer. Please try again later. (26). what is problem and how can i solve this.??

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/issues/221
