### ISSUE TITLE
getNotifications doesn't return correct invite number

### ISSUE THREAD

**Issue by shadypollen** [DoctorMcKay/node-steamcommunity#169]
```
community.getNotifications(function(err, notifications) {
     if (err) {
        console.log("Unable to get notifications: " + err);
     } else {
     console.log("Notification status: %j", notifications);
    }
    console.log(notifications.invites);
   });
```
So I'm calling this method when there's an outstanding friend invite(that does show up when I log in properly onto the account), however the output from the console is

`Notification status: {"comments":0,"items":0,"invites":0,"gifts":0,"chat":0,"trades":0}
`
Am I doing something wrong or could this be a bug?

**Comment by scholtzm** [comment]
Visit this URL with the same logged in account in your browser: `https://steamcommunity.com/actions/GetNotificationCounts`

You can see the mapping here: https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L327-L337

Does it match?
This might be an issue with Steam or the mapping has changed.

**Comment by shadypollen** [comment]
scholtzm, here's the output of that URL:

`{"notifications":{"4":0,"5":0,"6":1,"8":0,"9":0,"1":0,"2":0,"3":0,"10":0,"11":0}}`

So invites are shown correctly as 1 outstanding.

**Comment by Aareksio** [comment]
You are using outdated version of the module. Update please.

**Comment by shadypollen** [comment]
@Aareksio, updated to `3.30.7`, now I get this error:

```
/home/aleks/Documents/Programming/Javascript/tf2_bot/ult_bot.js:136
	console.log(notifications.invites);
	                         ^

TypeError: Cannot read property 'invites' of undefined

```

**Comment by Aareksio** [comment]
That's an error with your code. If `notifications` (2nd callback parameter) object is undefined, then there must been an error. The module is fine.

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

**Comment by shaunidiot** [comment]
Have you tried putting `console.log(notifications.invites);` **inside** the bottom else statement instead of **outside**?

**Comment by shadypollen** [comment]
@shaunidiot I got rid of it completely, it was just for debugging purposes.
@Aareksio Yes, I'll make post on the forum now that I know it's an issue with my script.

Thank you to everyone for their time.
