### ISSUE TITLE
enableTwoFactor status:29

### ISSUE THREAD

**Issue by JethroSovr** [DoctorMcKay/node-steamcommunity#170]
I want to get my shared_secret by using enableTwoFactor, because I cant get document from my iOS Steam APP.  Why I got error result  "DuplicateRequest"? 

Code:
var SteamUser = require('steam-user');
var SteamCommunity = require('steamcommunity');
var SteamTotp = require('steam-totp');
var fs = require('fs');
var SteamStore = require('steamstore');

var client = new SteamUser();

var logOnOptions = {
	"accountName": "xxxxx",
	"password": "xxxxxx",
	"twoFactorCode": "xxxxx"};

//Login
client.logOn(logOnOptions);
client.on('loggedOn', function() {
	console.log("Logged into Steam");
	client.enableTwoFactor(function() {
		for (var i = 0; i < arguments.length; i++) {
			console.log(arguments[i]);
		}
	});

});

//Log
Logged into Steam
body: { shared_secret: null,
  serial_number: null,
  revocation_code: null,
  uri: null,
  server_time: null,
  account_name: null,
  token_gid: null,
  identity_secret: null,
  secret_1: null,
  status: 29 }

**Comment by andrewda** [comment]
I'm guessing that means you already have two factor enabled.

**Comment by JethroSovr** [comment]
So  I cant use twoFactorCode ,to get my shared_secret?  So it only can use for a new count?

**Comment by andrewda** [comment]
If you disable two factor authentication and re-enable it using the `enableTwoFactor` method it will work fine. You just can't enable it again if it's already enabled.

**Comment by JethroSovr** [comment]
WOW,Let me try ... So,use enableTwoFactor is  same as  manually add TwoFactor on my phone,right?

**Comment by andrewda** [comment]
Yes

**Comment by JethroSovr** [comment]
Really appreciate for your great help~
