### ISSUE TITLE
How to get assetid of new items when user accepts tradeoffer?

### ISSUE THREAD

**Issue by gulshan98125** [DoctorMcKay/node-steamcommunity#173]
My bot sends offer to the user, how can I get the new asset ids of the items when the user accepts the offer?

**Comment by scholtzm** [comment]
Assuming you are using: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#getexchangedetailsgetdetailsiffailed-callback

**Comment by gulshan98125** [comment]
thanks a lot scholtzm!

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**
