### ISSUE TITLE
Editing profile fails under redirects

### ISSUE THREAD

**Issue by Kondax** [DoctorMcKay/node-steamcommunity#178]
When calling `editProfile` the request can be redirected with status code `302`. I passed in my own request object to specifically follow redirects but it seems as though [this fails on them](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L379). 

Line `379` seems to be ignoring redirects when calling `steamcommunity.com/my`. This will always result in a redirect though as it's only job is to redirect you to your profile. Not sure as to why it's been set to not follow the redirect.

**Comment by Kondax** [comment]
Hmm, it seems it's specifically checking for `302`, my bad. It must be the second request that fails with the redirect status code.

**Comment by Kondax** [comment]
I'm thinking that the issue is when setting a custom vanity URL the request is redirecting after being successfully set. This would explain the 302 status.

**Comment by waylaidwanderer** [comment]
Can confirm, I am also experiencing this issue. Definitely due to the customURL being set.
