### ISSUE TITLE
Hello, how get trade offer url?

### ISSUE THREAD

**Issue by slowas** [DoctorMcKay/node-steamcommunity#180]
Hello, 

I have question how get trade offer url?

**Comment by scholtzm** [comment]
From README.md:

> **Have a question about the module or coding in general? *Do not create a GitHub issue.* GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).
Such issues may be ignored!**

**Comment by DoctorMcKay** [comment]
While this is a good candidate for the forum, I think it probably would be a good thing to add the ability to get your trade URL directly to this module. Currently it's available in steam-tradeoffer-manager, but if you don't need trade handling and you only want your trade URL then that's a bit overkill. I'll mark this as a feature request.

**Comment by slowas** [comment]
I finded soliution is very simple https://steamcommunity.com/tradeoffer/{{ offer.id }}/

**Comment by DoctorMcKay** [comment]
Oh, that's all you were after? I interpreted your question as how you can get your account's trade URL.

I'll keep this issue open until I get that released in node-steamcommunity.

**Comment by DoctorMcKay** [comment]
`getTradeURL` was added in 3.33.0.
