### ISSUE TITLE
when i try to load inventory i get an error Cannot read property 'getSteamID64' of null

### ISSUE THREAD

**Issue by adWhy** [DoctorMcKay/node-steamcommunity#184]
const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const SteamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');
const config = require('./config.json');
 
const client = new SteamUser();
const community = new SteamCommunity();
const manager = new TradeOfferManager ({
    steam: client,
    community: community,
    language: 'en'
});
 
const logOnOptions = {
    accountName: config.username,
    password: config.password,
    twoFactorCode: SteamTotp.generateAuthCode(config.sharedSecret)
};
 
client.logOn(logOnOptions);
 
client.on('loggedOn', () => {
    console.log('succesfully logged on.');
    client.setPersona(SteamUser.Steam.EPersonaState.Online);
    client.gamesPlayed(["Custom Game",440]);
});
 
client.on("friendMessage", function(steamID, message) {
    if (message == "hi") {
        client.chatMessage(steamID, "hello, this works.");
    }
});
 
client.on('webSession', (sessionid, cookies) => {
    manager.setCookies(cookies);
 
    community.setCookies(cookies);
    community.startConfirmationChecker(20000, config.identitySecret);
});
 
function acceptOffer(offer) {
    offer.accept((err) => {
        community.checkConfirmations();
        console.log("We Accepted an offer");
        if (err) console.log("There was an error accepting the offer.");
    });
}
 
function declineOffer(offer) {
    offer.decline((err) => {
        console.log("We Declined an offer");
        if (err) console.log("There was an error declining the offer.");
    });
}
 
client.setOption("promptSteamGuardCode", false);
 
manager.on('newOffer', (offer) => {
    if (offer.partner.getSteamID64() === config.ownerID) {
        acceptOffer(offer);
    } else {
    declineOffer(offer);
    }
     
});

manager.getInventoryContents(730, 2, true, function (err, inventory){
    console.log(inventory);
});

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

You are trying to get your inventory before you're logged in.

**Comment by adWhy** [comment]
thank you
