### ISSUE TITLE
community.postUserComment returns Error: The settings on this account do not allow you to add comments. with a public profile. 

### ISSUE THREAD

**Issue by crazyzultan** [DoctorMcKay/node-steamcommunity#185]
I was testing this feature for a bot i'm making and after formatting everything right and passing the correct function arguments it all seems to work except that it errors with Error: The settings on this account do not allow you to add comments. Even though the profile I am trying to comment on has fully public visibility and commenting privacy settings.

**Comment by dasyah** [comment]
how you fix?
