### ISSUE TITLE
Gives wrong values for items.lowestPrice

### ISSUE THREAD

**Issue by jeanggi90** [DoctorMcKay/node-steamcommunity#19]
I'm programming a trade bot, and now I'm at the point where the bot has to read out the price of the items in the inventory. But unfortunately the outputted values are partly completly wrong...
Here the piece of code:

community.getMarketItem(appid.CSGO, market_hash_name, function(err, items) {
                if (err) {
                    Winston.error("Error getting Marketprice");
                } else {
                    Winston.info("Item " + market_hash_name + " is " + items.lowestPrice + " Cents worth");
                } 
            });

And this is the output which I got for a test (and obviously some prices are completly wrong...):

info: Item Glock-18 | Reactor (Field-Tested) is 108 Cents worth
info: Item Dual Berettas | Dualing Dragons (Field-Tested) is 560 Cents worth
info: Item Dual Berettas | Contractor (Field-Tested) is 69 Cents worth
info: Item P250 | Mint Kimono (Minimal Wear) is 18 Cents worth
info: Item Tec-9 | Army Mesh (Well-Worn) is 101 Cents worth
info: Item P250 | Boreal Forest (Well-Worn) is 212 Cents worth
info: Item USP-S | Torque (Factory New) is 31 Cents worth
info: Item MP9 | Orange Peel (Minimal Wear) is 294 Cents worth
info: Item AWP | Worm God (Field-Tested) is 73 Cents worth
info: Item MAC-10 | Candy Apple (Minimal Wear) is 259 Cents worth
info: Item G3SG1 | Jungle Dashed (Field-Tested) is 72 Cents worth
info: Item AWP | Worm God (Minimal Wear) is 80 Cents worth
info: Item SCAR-20 | Carbon Fiber (Factory New) is 294 Cents worth
info: Item Nova | Sand Dune (Minimal Wear) is 3 Cents worth
info: Item UMP-45 | Urban DDPAT (Battle-Scarred) is 3 Cents worth
info: Item PP-Bizon | Sand Dashed (Battle-Scarred) is 3 Cents worth
info: Item CZ75-Auto | Tigris (Field-Tested) is 21 Cents worth
info: Item SG 553 | Wave Spray (Factory New) is 165 Cents worth
info: Item SSG 08 | Blue Spruce (Minimal Wear) is 210 Cents worth
info: Item SG 553 | Wave Spray (Factory New) is 165 Cents worth
info: Item XM1014 | Blue Spruce (Battle-Scarred) is 70 Cents worth
info: Item USP-S | Serum (Minimal Wear) is 483 Cents worth
info: Item PP-Bizon | Antique (Minimal Wear) is 3999 Cents worth
info: Item P250 | Hive (Minimal Wear) is 52 Cents worth
info: Item Galil AR | Chatterbox (Battle-Scarred) is 980 Cents worth

**Comment by charredgrass** [comment]
This is where the code for that function is: https://github.com/DoctorMcKay/node-steamcommunity/blob/6feb607366de9ed0c25019bdddc3084143525f68/classes/CMarketItem.js#L6

It just uses the Steam API, so if it ends up returning a wrong price, it's just whatever the market price gave back.

**Comment by bulgakovk** [comment]
I reccomend you to use backpack.tf/api to get prices.

**Comment by Mikxail** [comment]
I've fixed it in #54
