### ISSUE TITLE
Support for trade wait in CEconItem

### ISSUE THREAD

**Issue by MattRh** [DoctorMcKay/node-steamcommunity#194]
Hi. Due to new CS:GO politics there appears some need to get time till item can be traded. As I understand, right now the only possibility is to write sommething like that
```
new Date(item.owner_descriptions ?
                item.owner_descriptions
                   .find((el) => el.type == 'html' && /Tradable After/.test(el.value))
                   .replace('Tradable After', '').trim() :
                null);
```
But this does not seem like a solid variant. Can you provide support for this property natively?

**Comment by DoctorMcKay** [comment]
Sorry, but I'm not particularly interested in adding specific stuff for one particular Steam game (popular though as it may be) to CEconItem, which is meant to be game-agnostic (as is the rest of the Steam economy system).

**Comment by MattRh** [comment]
Ok. Sad but true
