### ISSUE TITLE
Item position in inventory

### ISSUE THREAD

**Issue by MattRh** [DoctorMcKay/node-steamcommunity#195]
I didn't check. But code analysis shows that this code [components/users.js#L433-L436](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/users.js#L433-L436) may produce wrong item position in inventory in case, if tradableOnly === true. Is that a bug it is by design?

**Comment by Aareksio** [comment]
From [commit message](https://github.com/DoctorMcKay/node-steamcommunity/commit/35e6dd16e72509f9f0500b7a3f528a375d62ef35), it seems like `pos` was added for backwards compability, probably a design choice. Even if that's a bug, we can treat it as design choice by now, I don't think changing is worth the trouble with updating apps relying on position assigned with current method.

**Comment by DoctorMcKay** [comment]
I assume you're saying that `pos` should skip numbers when it skips tradable items, but that's not consistent with the old inventory endpoint which is what it's emulating.

**Comment by MattRh** [comment]
Ok, can close
