### ISSUE TITLE
Accessing firstAsset for non CSGO items?

### ISSUE THREAD

**Issue by jsieler** [DoctorMcKay/node-steamcommunity#196]
As of right now it is only possible to access item property "firstAsset" for CSGO only, since it is hardcoded: https://github.com/DoctorMcKay/node-steamcommunity/blob/master/classes/CMarketItem.js#L81
https://github.com/DoctorMcKay/node-steamcommunity/blob/master/classes/CMarketItem.js#L82

Is it possible to make it working for all available apps?

**Comment by DoctorMcKay** [comment]
Fixed in [3.35.2](https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.35.2).
