### ISSUE TITLE
Missing dependency to form-data

### ISSUE THREAD

**Issue by phiresky** [DoctorMcKay/node-steamcommunity#199]
https://github.com/DoctorMcKay/node-steamcommunity/blob/5e9c06bdc45b00909f94147c58a0fa6c711e3821/components/profile.js#L2 profile.js requires form-data, but this dependency is not specified in package.json. This causes `steamcommunity` to not work when installed via [pnpm](https://github.com/pnpm/pnpm).

**Comment by DoctorMcKay** [comment]
My bad. When developing I added it as a dependency then removed it but forgot to nuke the require. 3.36.1 fixes that.
