### ISSUE TITLE
Error: Can't find profile on comment method

### ISSUE THREAD

**Issue by dragonbanshee** [DoctorMcKay/node-steamcommunity#2]
Hi, I'm trying to create a function to post comments. Here's my code:
```javascript
var SteamCommunity = require('steamcommunity');
var community = new SteamCommunity();

var banshee = '76561198091343023';

function postComment(steamID, comment) {
    community.getSteamUser(steamID, function(err, user) {
        if(err) logger.error(err);
        else {
            user.comment(steamID, function(err) {
                if(err) logger.error(err);
            });
        }
    });
};

postComment(banshee, 'test comment');
```

Every time I try to do this, I get the error `The specified profile could not be found.`

My profile is not private, and comment permissions is public. As a matter of fact, I am trying to post a comment to my own profile, yet still get this error.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getsteamuserid-callback

The `steamID` parameter should be a `SteamID` object.
