### ISSUE TITLE
Add postUserStatus(status_text[,appid], callback)

### ISSUE THREAD

**Issue by Royalgamer06** [DoctorMcKay/node-steamcommunity#200]
This function will post your user status to https://steamcommunity.com/my/home
It could be done along the lines of this:
```
function postUserStatus(status_text, appid, callback) {
    var formdata = {
        sessionid: this.getSessionID(),
        status_text: status_text,
        appid: 0
    }
    if (appid) formdata.appid = appid;
    this.httpRequestPost(this.getProfileUrl() + "/ajaxpostuserstatus/", {
            formData: formdata,
            followAllRedirects: true
     }, (error, response, data) => { /* Error & callback handling */ });
}

function deleteUserStatus(postid, callback) {
    var formdata = {
        sessionid: this.getSessionID(),
        postid: postid
    }
    this.httpRequestPost(this.getProfileUrl() + "/ajaxdeleteuserstatus/", {
            formData: formdata,
            followAllRedirects: true
     }, (error, response, data) => { /* Error & callback handling */ });
}
```
Maybe support callback that includes any error that may have happened and the `postid` if success for `postUserStatus()`. 
Thank you

**Comment by Royalgamer06** [comment]
`/ajaxpostuserstatus` response example:
`{"success":true,"timestart":1524088800,"blotter_html":"/* large HTML string, parse to get postid? */","next_request":"https:\/\/steamcommunity.com\/id\/royalgamer06\/ajaxgetusernews\/?start=1524088800&startoffset=250"}`

`/ajaxdeleteuserstatus` response example:
`{"success":1}`

**Comment by Royalgamer06** [comment]
I've also discovered that the max length for `status_text` is 10240 characters.

**Comment by Royalgamer06** [comment]
I've noticed that quite a few times it returns an error for unable to parse JSON. Perhaps check what data says in those cases and return a more meaningful error. Actually, I'll try to help you with this.

**Comment by Royalgamer06** [comment]
It seems body is empty. Perhaps you are not following all redirects?

**Comment by Royalgamer06** [comment]
Nevermind, I checked out the code and it seems you are following all redirects.

**Comment by Royalgamer06** [comment]
Any idea why `body` is empty sometimes? I didn't have that issue with my personal code.

**Comment by DoctorMcKay** [comment]
Nope.
