### ISSUE TITLE
User.comment - undefined limits

### ISSUE THREAD

**Issue by fjexe** [DoctorMcKay/node-steamcommunity#204]
I can post a comment like (989 symbols):
`:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::`

I probably can use any other symbols and will be limited about 1000.
But when it comes to emoticons, I can not understand the logic of limits.

(660 symbols)
`:rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg::rg:`

- All ok. But if I add 2 more smiles (:rg::rg:) or Just text (aaaaaaaaaaaa) - I get: 

> An error occurred while commenting on user profile: Error: There was a problem posting your comment. Please try again.

Thus, the length of the comment with emoticons can be from 660 to ~900-1000 symbols. 
I also thought that there is a limit to emoticons, but here I did not find any logic.

Someone can explain how this limit works?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**
