### ISSUE TITLE
where get device id?

### ISSUE THREAD

**Issue by vejbuch** [DoctorMcKay/node-steamcommunity#21]
Hi where get device id?

Thanks

**Comment by DoctorMcKay** [comment]
What device ID?

**Comment by buddhapest** [comment]
prolly for 2FA?  you can pretty much make that up: https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/cxkn7q7

**Comment by DoctorMcKay** [comment]
I ask because afaik nothing in this library needs the user to provide it with a device ID.
