### ISSUE TITLE
Comment after succesfull trade?

### ISSUE THREAD

**Issue by kebaburmum** [DoctorMcKay/node-steamcommunity#214]
Hello idk if its here or not, but can someone send me a node.js code of how to make the bot post a +rep on the users profile after trading with him?

**Comment by nightfuryninja** [comment]
I believe this is the wrong place to ask but I will leave a response for you here. (I think here was the place to ask as it was not an issue but a general query).

All you need to do is call this method after accepting the trade. https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamUser#commentmessage-callback
