### ISSUE TITLE
comment bug

### ISSUE THREAD

**Issue by maxwell187** [DoctorMcKay/node-steamcommunity#217]
`client.on("friendMessage", function(steamID, message) {`
  `if (message == "r!comment") {`
   ` client.chatMessage(steamID, "We commented!")`
    `community.postUserComment("test")`
  `}`

Im getting no errors or anything else, it just wont send the comment.
I have permissions to comment on the profile, and the profile is not private.

**Comment by DoctorMcKay** [comment]
You're not getting an error because you don't have a callback.

**Comment by maxwell187** [comment]
Got my error now, it says that the account has not the permission to comment. But: the other account is public and the comments are also public.

**Comment by DoctorMcKay** [comment]
I just confirmed that it still works for me, so it's likely that you've tripped some kind of anti-spam measure in Steam.
