### ISSUE TITLE
join([callback]) no error but still not joined the group

### ISSUE THREAD

**Issue by Jxzzy1337** [DoctorMcKay/node-steamcommunity#223]
![Unbenannt](https://user-images.githubusercontent.com/49866690/57863584-a37e3f00-77fa-11e9-992b-012b639abd71.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/49866690/57863612-b1cc5b00-77fa-11e9-8312-a8083c64215a.PNG)

I don´t know what I can do, help please :(

**Comment by DoctorMcKay** [comment]
How do you know there was no error if you aren't checking for one?

**Comment by Jxzzy1337** [comment]
Thanks for your fast reply, I thought that "function(err) would do that

**Comment by DoctorMcKay** [comment]
No, you have to check if `err` is null (no error) or not.

**Comment by Jxzzy1337** [comment]
if (err == 'null')
{
console.log(colors.joined + "[" + account.username + "] Successfully joined Group.");
}

Is it possible to check it like that?

**Comment by DoctorMcKay** [comment]
No, `'null'` is a string containing the word "null". Get rid of the quotes.

**Comment by Jxzzy1337** [comment]
Oh, yes it has an error, now I have to look up why :/ thanks for your help untill now!

**Comment by DoctorMcKay** [comment]
If there's an error, `err` is an Error object. You can use `console.log(err)` to get an error message.

**Comment by Jxzzy1337** [comment]
Client 0 Logged into Steam.
Failed to Join the Group.
Error: Not Logged In

Do you have any suggestions, why this happens? :/

**Comment by andrewda** [comment]
Try moving your group joining code to a `webSession` event listener like so:

```javascript
client.on('webSession', (sessionid, cookies) => {
    community.setCookies(cookies);

    community.joinGroup('...', (err) => {
        if (err) {
            console.log('Failed to join group.');
            console.log(err);
        } else {
            console.log('Successfully joined group!');
        }
    });
});
```

I believe the problem with your code snippet is that you're logging in with the `SteamUser()` instance, but your `SteamCommunity()` instance never knows it's logged in. Setting the cookies with `community.setCookies(cookies)` in the code above will make sure that your Steam Community instance is also logged in.

**Comment by Jxzzy1337** [comment]
> Try moving your group joining code to a `webSession` event listener like so:
> 
> ```js
> client.on('webSession', (sessionid, cookies) => {
>     community.setCookies(cookies);
> 
>     community.joinGroup('...', (err) => {
>         if (err) {
>             console.log('Failed to join group.');
>             console.log(err);
>         } else {
>             console.log('Successfully joined group!');
>         }
>     });
> });
> ```
> 
> I believe the problem with your code snippet is that you're logging in with the `SteamUser()` instance, but your `SteamCommunity()` instance never knows it's logged in. Setting the cookies with `community.setCookies(cookies)` in the code above will make sure that your Steam Community instance is also logged in.

Thank You so much!! I finally got it. ♥
