### ISSUE TITLE
Enhancement reggards Inventory loading

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steamcommunity#227]
In the load inventory function, there is a temp var that temp caches data about the target inventory to be loaded, thats great, but it would be even greater if we had the possibility to cache that data in somewhere else, like a MongoDB or Mysql database, this would probably save some memory usage, and also, if the user have multiple bots, and if in any chances more than 1 bot try to load the same inventory, it would speed up even more by having just one global cache data..

an awesome solution would be to implement the node-steam-user system storage data =D

**Comment by DoctorMcKay** [comment]
I think this is outside of scope for node-steamcommunity. If you want to cache inventories, you should implement such a cache yourself.
