### ISSUE TITLE
postUserComment Problem

### ISSUE THREAD

**Issue by NetLuiz** [DoctorMcKay/node-steamcommunity#231]
When I try to leave comment i get the error below:
The settings on this account do not allow you to add comments.
I tried to do this on multiple users and none of them worked. I enabled comments from Privacy Settings.
My code:
```javascript
client.on("friendMessage", function(steamID) {
  community.postUserComment(steamID, "Test", function (err) {
    console.log(err);
  })
})

**Comment by DoctorMcKay** [comment]
Duplicate of #217
