### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by Heartz66** [DoctorMcKay/node-steamcommunity#240]
```
TypeError: callback is not a function
at /home/node/bots/source/node_modules/steamcommunity/components/confirmations.js:165:5
at ClientRequest.<anonymous> (/home/node/bots/source/node_modules/steamcommunity/node_modules/steam-totp/index.js:134:3)
```

I suspect `acceptConfirmationForObject` from causing this error.

**Comment by DoctorMcKay** [comment]
Going to need to see the code that's generating this.

**Comment by Heartz66** [comment]
error thrown at: https://github.com/DoctorMcKay/node-steamcommunity/blob/6eec88d1962e042e4725d1781ed5c4d5e78ad86a/components/confirmations.js#L184

I did not use the callback function in the `acceptConfirmationForObject` function.
