### ISSUE TITLE
Help me with firstCommunity.getTradeURL, please

### ISSUE THREAD

**Issue by wiktor00013** [DoctorMcKay/node-steamcommunity#241]
client.on("friendMessage", function (steamID, message) {
        if (steamID == admin && message == w[0]) {
			 client.chatMessage(steamID, "Comment");
				client.gamesPlayed(730);	
					
				community.comment(admin,"+rep");		
		}
});

Not working community.comment please help 
i try community.postUserComment(admin, "+REP" but not working

error: Error: The settings on this account do not allow you to add comments.

**Comment by andrewda** [comment]
The error message seems pretty self-explanatory. It's likely that either the user's permissions are such that your account isn't allowed to post comments, or, as mentioned in https://github.com/DoctorMcKay/node-steamcommunity/issues/217#issuecomment-469521228, you tripped a Steam anti-spam guard.
