### ISSUE TITLE
steamcommunity\components\helpers.js:4. Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by pikachuexeallen** [DoctorMcKay/node-steamcommunity#242]
D:\SteamBot>node bot.js
D:\SteamBot\node_modules\steamcommunity\components\helpers.js:4
        var keys = Object.keys(input);
                          ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.isSteamID (D:\SteamBotProject\MyBot\node_modules\[4msteamcommunity[24m\components\helpers.js:4:20)
    at SteamCommunity.getSteamUser (D:\SteamBotProject\MyBot\node_modules\[4msteamcommunity[24m\classes\CSteamUser.js:7:40)
    at Object.<anonymous> (D:\SteamBotProject\MyBot\bot.js:35:28)
[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m
### My code
const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const SteamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');
const config = require('./config.json');

const client = new SteamUser();
const community = new SteamCommunity();
const manager = new TradeOfferManager ({
	steam: client,
	community: community,
	language: 'en'
});

const logOnOptions = {
	accountName: config.username,
	password: config.password,
	twoFactorCode: SteamTotp.generateAuthCode(config.sharedSecret)
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('succesfully logged on.');
	client.setPersona(1);
	client.gamesPlayed(["Custom Game",730]);
});

client.on("friendMessage", function(steamID, message) {
	if (message == "hi") {
		client.chatMessage(steamID, "hello, this works.");
	}
});

client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies);

	community.setCookies(cookies);
	community.startConfirmationChecker(20000, config.identitySecret);
});

function acceptOffer(offer) {
	offer.accept((err) => {
		community.checkConfirmations();
		console.log("We Accepted an offer");
		if (err) console.log("There was an error accepting the offer.");
	});
}

function declineOffer(offer) {
	offer.decline((err) => {
		console.log("We Declined an offer");
		if (err) console.log("There was an error declining the offer.");
	});
}

manager.on('newOffer', (offer) => {
	if (offer.partner.getSteamID64() === config.ownerID) {
		acceptOffer(offer);
	} else {
	declineOffer(offer);
	}
     
});

**Comment by DoctorMcKay** [comment]
From that stack trace, it looks like you're calling `getSteamUser()` without an argument on bot.js line 35.

Also, don't use the confirmation checker.

**Comment by pikachuexeallen** [comment]
solved the problem. Thank you
