### ISSUE TITLE
memberSince different what user see in offer

### ISSUE THREAD

**Issue by DarkGL3** [DoctorMcKay/node-steamcommunity#243]
I noticed that date returned by memberSince differs what user see when he go to the offer created by account ( by 1 day )

Is it just timezones thing or something else ?

**Comment by Heartz66** [comment]
Data returned to you is probably UTC so you need to convert it to your own timezone somehow, I use momentjs local function to take care of it

**Comment by DarkGL3** [comment]
It was my first thought to, but I doesn't make sense when I test it with different timezones ( +1 day difference ). 

Can you share the code which you use ?

**Comment by DoctorMcKay** [comment]
I believe it's a timezone issue. Not sure there's any real way to fix this; you should probably use the WebAPI to get user data anyway.
