### ISSUE TITLE
SteamCommunity sessionexpired

### ISSUE THREAD

**Issue by nicdnepr** [DoctorMcKay/node-steamcommunity#244]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#sessionexpired
How much time before raise event sessionexpired?
Is any action for extending sessionexpired?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

There's no real clear time interval for when sessions expire. You just need to refresh your session when it happens.
