### ISSUE TITLE
adjust to new steam api changes

### ISSUE THREAD

**Issue by MMMMasterM** [DoctorMcKay/node-steamcommunity#249]
enableTwoFactor always throws error "Malformed Response" now on a non-limited account with verified phone number and disabled 2FA. 

The exact code worked in the past. 
Api probably broke due to steam's chat rework. 

Similarly the process of adding+verifying a phone number now includes an extra step where it wait's for an additional email verification. This breaks the previously working addPhoneNumber+verifyPhoneNumber api. 

Anyway, thank you for your great library! :)

**Comment by DoctorMcKay** [comment]
I am unable to reproduce this; I'm guessing that Steam reverted whatever behavior it changed.

Please reopen if you're still having issues with this.

**Comment by DoctorMcKay** [comment]
Actually, I think I know why this was happening. I've updated the docs accordingly: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#enabletwofactorcallback
