### ISSUE TITLE
 community.startConfirmationsChecker is not a function

### ISSUE THREAD

**Issue by hub4-try** [DoctorMcKay/node-steamcommunity#253]
Can somebody help me?

client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies);
	community.setCookies(cookies);
	community.startConfirmationsChecker(20000, config.identitySecret);
});

**Comment by Mr-VIT** [comment]
startConfirmation**~~S~~**Checker

**Comment by DoctorMcKay** [comment]
![image](https://user-images.githubusercontent.com/1538723/85348246-fda30680-b4c8-11ea-9f90-f13b369635c8.png)
