### ISSUE TITLE
openBoosterPack documentation and changelog missing

### ISSUE THREAD

**Issue by itsjfx** [DoctorMcKay/node-steamcommunity#256]
Hey, sorry if an issue is an inappropriate place to raise this - but when you merged my PR: https://github.com/DoctorMcKay/node-steamcommunity/pull/250 for openBoosterPack you never added any documentation to the wiki for it.

It's also missing from the 3.41.5 release log: https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.41.5 - see commit log: https://github.com/DoctorMcKay/node-steamcommunity/commits/master to see when it should have been added.

Also note I added some base documentation in my PR as a skeleton which should help you with the doc for the wiki :)

**Comment by DoctorMcKay** [comment]
Sorry about the delay; I've updated the docs now.
