### ISSUE TITLE
question about sending steam profile edit data

### ISSUE THREAD

**Issue by 05e** [DoctorMcKay/node-steamcommunity#281]
I'm trying to replicate your `editProfile` function in c#, I have all the previous user's settings (`existingSettings` in your case) but can't seem to figure out how to send them to Steam. Right now, when I send my data (which I am sending as `"application/json"` after serializing a c# object which I put below) all I get is a redirect to what I believe is the /my/edit/info page, and no profile editing occurs. 

I read a previous issue on here that said the `customURL` parameter may be causing this, but even when i remove that from my object i get the same redirect and no change in the profile.

I was wondering if you could put me in the right path regarding structuring my post request to the steam edit page? Do i need to have all parameters in the request, even the ones I'm not trying to change? (looking at how requests are done with steam on their website, even if i change just my name the request sends the whole information including `customURL`, `country`, etc.) Do i need to send my data not as `"application/json"` but instead `"multipart/form-data"`? (which is how it's done on the website). Where can I find in your project the event listener for `'postHttpRequest'` (which you emit [here](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/http.js#L55)).

My object in c#:
```cs
object data = new
{
    sessionID = sessionId,
    type = "profileSave",
    weblink_1_title = "", 
    weblink_1_url = "",
    weblink_2_title = "",
    weblink_2_url = "",
    weblink_3_title = "",
    weblink_3_url = "",
    personaName = "change this please",
    real_name = userInfo["strRealName"], //these are JObject values but they hold strings
    summary = userInfo["strSummary"],
    country = userInfo["LocationData"]["locCountryCode"],
    state = userInfo["LocationData"]["locStateCode"],
    city = userInfo["LocationData"]["locCityCode"],
    customURL = userInfo["strCustomURL"],
    json = 1
};
```

Thanks in advance

**Comment by Preport** [comment]
I believe you have to send a form 
https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/profile.js#L134
as seen here ^

and your request should look like this https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L523

And yes you have to send everything including stuff you haven't changed cause it's not an upsert.
