### ISSUE TITLE
Communication node-steamtradeoffers

### ISSUE THREAD

**Issue by GAMELASTER** [DoctorMcKay/node-steamcommunity#30]
Hello,

I using a node-steamcommunity as replace of node-steam. Actually, i want to make workinga node-steamtradeoffers with node-steamcommunity, but actually, node-steamcommunity not contains a events, for sample as in node-steam "steam.on('tradeOffers'...", and i think to port a trade offer code to node-steam-tradeoffer-manager takes a really so much time for me becouse that part contains alot of code.

So my question is, its possible to make a event when trade offers come, or how to make running steamcommunity with node-steam, but main logger has been a node-steamcommunity?

Thanks

**Comment by scholtzm** [comment]
You are trying to replace apple with orange here.The libraries are somewhat different.

You could poll [`getNotifications`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getnotificationscallback) but there is no reason to stop using node-steam. You can use node-steamcommunity as an additional module to deal with confirmations.

**Comment by GAMELASTER** [comment]
@scholtzm Yes i know, actually solved, i just used a another package for confirmate a trades!

Ale aj tak, Vďaka :-)

**Comment by DoctorMcKay** [comment]
DoctorMcKay/node-steam-tradeoffer-manager might be worth looking into. It automatically polls offers. Using it with node-steamcommunity works just fine and you don't need a Steam client.

**Comment by GAMELASTER** [comment]
@DoctorMcKay yes i know, but as i said upper (but wrongly), its takes a long time to rewrite a steam-tradeoffers functions to node-steam-tradeoffer-manager.

In close time i want to rewrite all, so i will use that!

Thanks
