### ISSUE TITLE
Error: Malformed response

### ISSUE THREAD

**Issue by pcheloveker** [DoctorMcKay/node-steamcommunity#308]
Today, when executing the "login" method, I get the error: "Malformed response"
This happens on all my accounts, none of them can log in.
"steamcommunity": "^3.44.3"

**Comment by kjljxybr** [comment]
got the same error, fixed with `disableMobile: true` in login params

**Comment by hovik-geodakyan** [comment]
Steam removed oauth token from mobile login response. This will help if u want to still use mobile login.
https://github.com/DoctorMcKay/node-steamcommunity/pull/309

**Comment by hovik-geodakyan** [comment]
> > Steam removed oauth token from mobile login response. This will help if u want to still use mobile login.
> > #309
> 
> Do I understand correctly that there is no difference `disableMobile: true/false`, OAuthToken is no longer available?

As far as we understand, yes, the token was removed today. Can't say if that was intentional or due to a bug on steam's end.

However we still want to be able to login imitating mobile client.

**Comment by logan12344** [comment]
But what to do with steamguard, oAuthToken? Both 0

**Comment by logan12344** [comment]
I cant use oAuthLogin without them

**Comment by DoctorMcKay** [comment]
Fixed in [3.44.4](https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.44.4).
