### ISSUE TITLE
acceptConfirmationForObject not working

### ISSUE THREAD

**Issue by mariusriedl** [DoctorMcKay/node-steamcommunity#310]
community.acceptConfirmationForObject doesn't work anymore, according to https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/844#issuecomment-1599739325, Steam rolled out an update that breaks this

**Comment by zhengoogle** [comment]
same problem

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.45.1
