### ISSUE TITLE
Can't confirm trade offer: Error: HTTP error 404

### ISSUE THREAD

**Issue by mariusriedl** [DoctorMcKay/node-steamcommunity#312]
Hi, I'm using acceptConfirmationForObject like usual. Confirming trades worked last night, now we're getting 404s.

```
if (status == "pending") {
    community.acceptConfirmationForObject(identitySecret, offer.id, function (err) {
        if (err) {
            console.log("Can't confirm trade offer " + offer.id + ": " + err);
        } else {
            console.log("Trade offer " + offer.id + " confirmed");
        }
    });
}
```

Not sure whats up right now, I'll investigate further, and keep this issue open until I know more.
Steam community servers are online (https://steamstat.us/), so what I suspect is they made some change to their infrastructure.

Feel free to advise me if I'm making a mistake and close this issue.

**Comment by mariusriedl** [comment]
Item name: P90 | Sunset Lily (Field-Tested)
Found item: 'P90 | Sunset Lily (Field-Tested)'
Trade offer XXXXXXXXX sent
Can't confirm trade offer XXXXXXXXX: Error: HTTP error 404

**Comment by DoctorMcKay** [comment]
npm update

**Comment by mariusriedl** [comment]
lol sorry

**Comment by DoctorMcKay** [comment]
All good, take care.
