### ISSUE TITLE
Resolving vanity returns error

### ISSUE THREAD

**Issue by HerrEurobeat** [DoctorMcKay/node-steamcommunity#313]
Hey! Resolving the vanity of a user returns an error when attempting to create a SteamID object:
```
TypeError: input.match is not a function
    at new SteamID (.../node_modules/steamcommunity/node_modules/steamid/index.js:72:23)
    at .../node_modules/steamcommunity/classes/CSteamSharedFile.js:148:24
    at .../node_modules/steamcommunity/components/helpers.js:109:4
```

**Comment by HerrEurobeat** [comment]
> > node_modules/steamid/
> 
> You probably want to open an issue [there](https://github.com/DoctorMcKay/node-steamid/issues) instead.

No, the issue inside the resolveVanityURL helper

**Comment by DoctorMcKay** [comment]
:+1: Thanks

**Comment by HerrEurobeat** [comment]
I just got bug reports from two users that this still seems to fail when the profile is private.  
It looks like Steam does not include the `customURL` key inside the xml response for private profiles for some reason. 

I'll open a PR in a few minutes that should fix this bug as well by parsing the function's url parameter instead of getting it from the XML data.
