### ISSUE TITLE
Re-enabling mobile guard

### ISSUE THREAD

**Issue by naksuasd** [DoctorMcKay/node-steamcommunity#33]
Hi. If i re-enable mobile guard, do i need to wait 7 days again, and will i be trade banned at 9. december?
Am i right i need to do it in case i want to use this library to confirm mobile guard trades?

**Comment by DoctorMcKay** [comment]
No, it won't deauthorize your devices. Yes, you will have escrow on December 9th. Yes, you need to do so if you don't have your secret and can't root/jailbreak your phone.

**Comment by naksuasd** [comment]
I have rooted galaxy, how i can get it with it?

**Comment by DoctorMcKay** [comment]
Sounds like you found it.

**Comment by naksuasd** [comment]
Thank you, issue closed.
