### ISSUE TITLE
Bot logging in error

### ISSUE THREAD

**Issue by BoyKaYK** [DoctorMcKay/node-steamcommunity#331]
hi, about 2 days ago i started get this error during steam logging in and getting an account data:  
![image](https://github.com/DoctorMcKay/node-steamcommunity/assets/88595925/9c3aa3f2-916b-4142-9b22-41ccdf5f15e4)
Before i started getting this error i didn't make any changes in code and everything works fine.
Just already updatet all my packages, and still in doesn't work (

Here is a code of getAccountData func i get an error from
![image](https://github.com/DoctorMcKay/node-steamcommunity/assets/88595925/d2c091dc-7fc8-4037-b4ee-1d23de0131e2)

Will be grateful for any help

**Comment by DoctorMcKay** [comment]
Please see here for info about changes to cookies: https://github.com/DoctorMcKay/node-steam-session/releases/tag/v1.7.2
