### ISSUE TITLE
Injecting proxy - please confirm it's correct :)

### ISSUE THREAD

**Issue by aligatorr89** [DoctorMcKay/node-steamcommunity#336]
Hi @DoctorMcKay , sorry for tagging, i will reward you for the answer !

I'm using proxy with steamcommunity. 

For login I use `steam-session` library, and for sending requests to steamcommunity i use this package (steam-community).

Is this correct way of injecting proxy? (I know i shouldn't use login from this package, that's why i use `steam-session`)

``` typescript
    const community = new SteamCommunity({
      request: Request.defaults({
        forever: true,
        proxy: 'http://my-proxy.com',
      }),
    });
```

**Comment by DoctorMcKay** [comment]
Yes, that looks fine.
