### ISSUE TITLE
Login doesn't work with twoFactorCode

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steamcommunity#34]
I am trying to login to steamcommunity, but I am having trouble, it says ```[Error: SteamGuardMobile]```
```
        bot.community.login({
            'accountName': botDocument.username,
            'password': botDocument.password,
            'twoFactorCode': SteamTotp.generateAuthCode(botDocument.twoFactor.sharedSecret)
        }, function (err, sessionId, cookies, steamguard) {
        });
```

On my console, I turned on some debugs and I got from your code:
[```details```](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L39) object:
```
{ 
  accountName: 'XXX',
  password: 'XXX',
  twoFactorCode: 'CJBT5' 
}
```
[```form```](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L81-L94) object:
```
{ 
  captcha_text: '',
  captchagid: -1,
  emailauth: '',
  emailsteamid: '',
  password: 'XXX',
  remember_login: 'true',
  rsatimestamp: '410760900000',
  twofactorcode: 'CJBT5',
  username: 'XXX',
  oauth_client_id: 'DE45CD61',
  oauth_scope: 'read_profile write_profile read_client write_client',
  loginfriendlyname: '#login_emailauth_friendlyname_mobile' 
}
```

And finally the response from [steam](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L112-L114):
```
{ 
  success: false, 
  requires_twofactor: true, 
  message: '' 
}
```

Response:
```
[Error: SteamGuardMobile]
```

**Comment by DoctorMcKay** [comment]
IS your time correct?

**Comment by andrewda** [comment]
And have you already used that code to login?

**Comment by dolanmiu** [comment]
I have used that already to login yes

I login with ```node-steam-user``` first then login next with ```node-steamcommunity```

**Comment by DoctorMcKay** [comment]
Codes are not reusable.

You shouldn't be logging in separately. Listen for the `webSession` event in steam-user and then call `setCookies` in steamcommunity with those cookies.

**Comment by dolanmiu** [comment]
Thanks, worked perfectly after setting cookies

**Comment by adaptivedev** [comment]
Do I need to use client.logOn as per SteamUser? Otherwise how can I get the cookies?
Details and code: https://gist.github.com/adaptivedev/e1e4774715c06d5eaf87

**Comment by DoctorMcKay** [comment]
Please don't hijack closed issues. If you have a question ask in the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).
