### ISSUE TITLE
Get assetid of item after trade (receipt)

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steamcommunity#35]
I am aware that the ```assetid``` changes when you trade an item. 

I want to get the NEW ```assetid``` when it is traded into my bot.

How would I accomplish this?

[```node-steam-tradeoffers```](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/index.js#L351-L388) has a function which does [this](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/index.js#L351-L388) by getting the "receipt", but it does not work correctly for me, and soon I want to be migrating to your libraries for handling steam trade offers.

**Comment by dolanmiu** [comment]
I have found ```getOffer(id, callback)``` in [```node-steam-tradeoffer-manager```](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#getofferid-callback).

Does this get the new ```assetid```?

**Comment by DoctorMcKay** [comment]
Use `offer.getReceivedItems` to pull the new data from the receipt page. It works well in my experience.
