### ISSUE TITLE
Can't use getConfirmations with getConfirmationKey: incorrect codes.

### ISSUE THREAD

**Issue by zharikovpro** [DoctorMcKay/node-steamcommunity#36]
Hello!

Trying to use steamcommunity paired with totp and wrote small example to list pending mobile confirmations. Of course I want to confirm them later, and already stuck. Login with generateAuthCode works fine, and after that I get:

> Logging in
> Get confirmations
> getConfirmations result
> [Error: It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caused by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on this device is no longer valid.]

```
var SteamCommunity = require('steamcommunity');
var SteamTotp = require('steam-totp');

var community = new SteamCommunity();
var shared_secret = 'secret=';

var login_details = {
  "accountName": login,
  "password": password,
  "steamguard": steamguard,
  "twoFactorCode": SteamTotp.generateAuthCode(shared_secret)
}

console.log('Logging in');
community.login(login_details, function(err, session_id, cookies, steamguard) {
  if (err) {
    console.dir(err);
  } else {
    console.log('Get confirmations');
    time = Math.floor(Date.now() / 1000);
    key = SteamTotp.getConfirmationKey(shared_secret, time, 'conf');

    community.getConfirmations(time, key, function (err, confirmations) {
      console.log('getConfirmations result');
      console.dir(err);
      console.dir(confirmations);
    });
  }
});
```

I don't know how to check if it's a problem with steamcommunity or totp itself. I can do whatever it takes to fix it, just need some clues. Thank you for great modules and awesome work!

**Comment by DoctorMcKay** [comment]
You should use identity_secret for confirmations, not shared_secret.

**Comment by adaptivedev** [comment]
what is "steamguard" from, how do you get that?
