### ISSUE TITLE
Convert sentry file to steamguard?

### ISSUE THREAD

**Issue by trzyrazyzero** [DoctorMcKay/node-steamcommunity#37]
It is possible?

**Comment by DoctorMcKay** [comment]
No.

**Comment by trzyrazyzero** [comment]
So i must wait 7 days if i dont have steamguard file?

**Comment by DoctorMcKay** [comment]
Yes.

**Comment by DoctorMcKay** [comment]
Yes.

**Comment by trzyrazyzero** [comment]
Ok, thanks for fast response.

**Comment by srabouin** [comment]
Couldn't you just use your browser cookies and use that to access offers so you don't need to wait 7 days?
