### ISSUE TITLE
enableTwoFactor -> Error: This account is not authorized to use this feature.

### ISSUE THREAD

**Issue by kingjerod** [DoctorMcKay/node-steamcommunity#39]
I've been trying to use steamcommunity to enable 2FA for several of my accounts. When calling enableTwoFactor, it returns the error "This account is not authorized to use this feature."

I've gotten it to work for 1 of my accounts, but for several others it will not work. Those accounts have money on them, and have a phone number setup. I've enabled/disabled 2FA for all of those accounts multiple times using both the mobile app and also [Steam Desktop Authenticator](https://github.com/Jessecar96/SteamDesktopAuthenticator). So it would seem it's not the accounts, but something in this library.

If it helps, I was using Vapor (v1.0) to connect, calling community.setCookies, then enableTwoFactor. Sorry I can't provide much more information. I've seen other people post the same problem on Reddit/r/SteamBot. 

I've been able to bypass this problem by copying over the maFile that SteamDesktopAuthenticator generates, and having Steam TOTP use that.

**Comment by DoctorMcKay** [comment]
If you don't login directly through steamcommunity, it needs to load [webchat](https://steamcommunity.com/chat) to get an oauth token for the WebAPI. Steam denies this at its whim.

**Comment by kingjerod** [comment]
Thanks for the quick response. So there is no way to pass the OAuth token to steam community otherwise?

**Comment by DoctorMcKay** [comment]
No. Those are the only two ways to get one.
