### ISSUE TITLE
Purpose of steamguard string if using steam mobile authenticator?

### ISSUE THREAD

**Issue by Afterglow375** [DoctorMcKay/node-steamcommunity#4]
This may be more of a documentation update than anything. Something that's confusing to me is when logging in with a "twoFactorCode", you receive a steamguard string in the callback. How am I even getting a steam guard string back and what's the point of it? I can't login with it; I just get a "SteamGuardMobile" error if I try.

**Comment by DoctorMcKay** [comment]
It's what records your tradability. If you want to use this with [`node-steam-tradeoffer-manager`](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager) or the like, you'll need a 7-day-old `steamguard` string.

If not, then you don't really need to record it I suppose.
