### ISSUE TITLE
Join and Leave SteamGroup not working

### ISSUE THREAD

**Issue by fluxX04** [DoctorMcKay/node-steamcommunity#42]
Hello,

currently i'am testing the join and leave group functions but they won't work.
Tested the CSteamGroup methode and the non-object method.

**Join:**
```javascript
var id = new SteamID("103582791429521592");
id.type = SteamID.Type.CLAN;

steamCommunity.getSteamGroup(id, function(err, group) {
	if (err) {
		logger.info('1.0 > ' + err);
	} else {
		group.join(function(err) {
			if (err) {
				logger.info('1.1 > ' + err);
			}
		});
	}
	
});
				
steamCommunity.joinGroup("103582791429521592", function(err) {
	if (err) {
		logger.info('2.0 > ' + err);
	}
});
```
No error but the bot didn't joined the group.

**Leave:** (bot is in the group)
```javascript
var id = new SteamID("103582791434636960");
id.type = SteamID.Type.CLAN;

steamCommunity.getSteamGroup(id, function(err, group) {
	if (err) {
		logger.info('1.0 > ' + err);
	} else {
		group.leave(function(err) {
			if (err) {
				logger.info('1.1 > ' + err);
			}
		});
	}
	
});

steamCommunity.leaveGroup("103582791434636960", function(err) {
	if (err) {
		logger.info('2.0 > ' + err);
	}
});
```
Error:
`info: 2.0 > Can't get profile URL`
`info: 1.1 > Can't get profile URL`

So is my code wrong or is it a bug?

Thanks,
Greetz

**Comment by fluxX04** [comment]
Any updates? - to clarify my code is not the problem.

**Comment by DoctorMcKay** [comment]
Are you sure that you're logged in?

**Comment by fluxX04** [comment]
No Problem. 
Yeah my bad, wasn't logged in - thought only steam-user login is enough.
Anyway it's working now, thanks!

**Comment by scholtzm** [comment]
You can use setCookies so you don't have to manage multiple logins.

**Comment by fluxX04** [comment]
oh, works now with setCookies - thanks for the heads-up!
