### ISSUE TITLE
getConfirmations error

### ISSUE THREAD

**Issue by pavell-hyuna** [DoctorMcKay/node-steamcommunity#43]
Hello . I got this error when i try to get confirmations: 
"It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caused by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on this device is no longer valid"

here is my code . Maybe someone can help me 

```javascript
community.login(details, function(err, sessionID, cookies, steamguard) {
	if(err) {
		throw(err);
	}else {

	    console.log('Getting confirmations');
	    var time = Math.floor(Date.now() / 1000);
	    var key = SteamTotp.getConfirmationKey(identity_secret, time, 'conf');
		
	    console.log('Time now : ');
	    console.log(time);
	    console.log('-----');


		community.getConfirmations(time, key, function (err, confirmations) {
	      console.log('getConfirmations result');
	      console.dir(err);
	      console.dir(confirmations);
    	});

	}
	console.log('Logged in');
});
```

**Comment by DoctorMcKay** [comment]
Either your clock is wrong or your identity_secret is wrong.

**Comment by pavell-hyuna** [comment]
Thanks for your reply. I think identity_secret is good ( it's not shared secret ) . Maybe it's clock . Any ideas how to fix it ? Because i'm working on it for 1.5 hour and i can't find a solution . Can it be an issue with ios / android ?

**Comment by pavell-hyuna** [comment]
I saw that my "time" variable return timestamp for 1970 year. Can it be a problem ?

**Comment by DoctorMcKay** [comment]
Please post the value of your `time` variable here.

**Comment by pavell-hyuna** [comment]
Here is it 

1450273688

**Comment by srabouin** [comment]
That time is fine, you probably have the wrong identity secret, if you provide the wrong identity secret you get that error.

**Comment by pavell-hyuna** [comment]
I have got this secret from steamGuard . It's identity secret ( here is only numbers ) . I have got this from file + node-steamparser . Is it good or not ?

**Comment by pavell-hyuna** [comment]
this file is from ios device . 
can you give me example of identity secret ?

**Comment by pavell-hyuna** [comment]
my identity secret is something like "71566178250234722"

**Comment by scholtzm** [comment]
I'm pretty sure that's not your identity_secret. Looks like you might be using your SteamID as your idntity_secret. :grinning:

**Comment by pavell-hyuna** [comment]
it's from node-steamparser . I got info like this 

hared_secret ...: value
secret_1 ........: value
identity_secret .: value
revocation_code .: value
serial_number ...: value
steamguard_scheme: value
steamid .........: value
account_name ....:  value
token_gid .......: value

And i took it from identity_secret (value field)

**Comment by srabouin** [comment]
it's probably wrong then, I made that quickly with my own file, it's possible other files have a different order of things, didn't account for that -- I suggest using plutil instead to figure it out

**Comment by pavell-hyuna** [comment]
can you paste here how to use plutil ? I'm using linux mint

**Comment by pavell-hyuna** [comment]
or told me how to convert it :)

**Comment by DoctorMcKay** [comment]
Really, if you can't match keys to values then the quickest way to find it is to take the three base64 values (they look something like `cnOgv/KdpLoP6Nbh0GMkXkPXALQ=`) and try all 3 until you get one that works.

**Comment by srabouin** [comment]
plutil comes with iTunes, run plutil -p Steamguard-765611980XXXXXXX

**Comment by pavell-hyuna** [comment]
lol i take it from "steamid" field and all is working . But list of confirmations is empty :(

**Comment by pavell-hyuna** [comment]
As i understood it must be not empty . Because my php script found trade offers . After that i must confirm them and send or cancel . Is it right ? Guys thanks for your replies :)

**Comment by srabouin** [comment]
btw @pavell-hyuna i pushed a dynamic version for node-steamparser so you can test it out maybe, hope it works for you ;)

**Comment by ga83s** [comment]
did u figure it out ...im having the same issue and dont understand the identity_secret  and stuff like that? can someone please help me

**Comment by pavell-hyuna** [comment]
Yes i did . I just used wrong secret . You can try find string like cnOgv/KdpLoP6Nbh0GMkXkPXALQ= . For me it wasn't identity_secret ( it was another secret , can't remember )
