### ISSUE TITLE
Steam Confirmation Problem.

### ISSUE THREAD

**Issue by Unkn09wn** [DoctorMcKay/node-steamcommunity#46]
I have this error.

C:\xampp\htdocs\server\source\node_modules\steamcommunity\components\confirmations.js:145
        params.a = community.steamID.getSteamID64();
                                    ^

TypeError: Cannot read property 'getSteamID64' of undefined
    at request (C:\xampp\htdocs\server\source\node_modules\steamcommunity\components\confirmations.js:145:30)
    at SteamCommunity.getConfirmations (C:\xampp\htdocs\server\source\node_modules\steamcommunity\components\confirmatio
ns.js:17:2)
    at C:\xampp\htdocs\server\source\gamebot.js:126:35
    at SteamTradeOffers.<anonymous> (C:\xampp\htdocs\server\source\node_modules\steam-tradeoffers\index.js:309:7)
    at Request.self.callback (C:\xampp\htdocs\server\source\node_modules\request\request.js:198:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (C:\xampp\htdocs\server\source\node_modules\request\request.js:1035:10)
    at emitOne (events.js:83:20)
    at Request.emit (events.js:170:7)

And, my code is:

                        community.getConfirmations(Math.round(Date.now() / 1000), SteamTotp.getConfirmationKey('conf'), function(err, confirmations) {
                            if(err) return console.log(err);
                            console.log(confirmations);
                        });

Any idea? :sob:

**Comment by scholtzm** [comment]
Have you set the cookies are logged in via this module?

**Comment by Unkn09wn** [comment]
I'm using node-steam-user (for DoctorMcKay). And my login response code is:

client.on('loggedOn', function(details){
    clearInterval(relayToConnect);
    console.log(" ");
    client.on('webSession', function(sessionID, cookies){
        manager.setCookies(cookies, function(err) {
            if(err) {
                console.log(err);
                return;
            }
            offers.setup({
                sessionID: sessionID,
                webCookie: cookies,
                APIKey: manager.apiKey
            });

            /** Initial Bot **/
            client.setPersona(SteamUser.Steam.EPersonaState.Online);
            logger.info("Cookies almacenadas correctamente!");
            logger.info("Detalles de sesión almacenadas correctamente!");
            logger.info("Steam API Key: "+manager.apiKey+"\n");
            logger.info("Servicio de comunicaciones bi-direccional establecido. (PORT: "+steamBOT.ws_port+")");
            app.listen(steamBOT.ws_port);
            logger.info("================[ESPERANDO OFERTAS]================");
            OnBotUpdate();

            // Example
            offers.loadMyInventory({
                appId: 730,
                contextId: '2'
            }, function(err, items) {
                logger.info("Enviando objeto de comisión!");
                offers.makeOffer({
                    partnerAccountId: '256122643',
                    accessToken: '1tq1bGm8',
                    itemsFromMe: [{
                        appid: 730,
                        contextid: '2',
                        amount: 1,
                        assetid: '4503270004'
                    }],
                    itemsFromThem: [{}],
                    message: '',
                }, function(err, response) {
                    if(err) {
                        logger.error(err);
                    }
                    else {
                        logger.info("El objeto de comisión ha sido enviado correctamente.");
                        community.getConfirmations(Math.round(Date.now() / 1000), SteamTotp.getConfirmationKey('conf'), function(err, confirmations) {
                            if(err) return console.log(err);
                            console.log(confirmations);
                        });
                    }
                });
            });
        });
    });
});

**Comment by scholtzm** [comment]
What's `manager`?

And you are not logging in or setting cookies for `community` according to snippets you posted.

**Comment by Unkn09wn** [comment]
Manager is the library node-steam-tradeoffer-manager

I'm using the function client.logOn() for log in Steam.
but i need to use too the community.login() function?

**Comment by andrewda** [comment]
You don't need to call `community.login()`, just `community.setCookies()` should be fine.

**Comment by DoctorMcKay** [comment]
Please use the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/) for future questions.

**Comment by Unkn09wn** [comment]
Okay. I'm fixed the problem. But drop this error. 

"[Error: It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caus
ed by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a
 different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on th
is device is no longer valid.]".

I'll take a look at this post [https://github.com/DoctorMcKay/node-steamcommunity/issues/43] to inform me about this. Thanks to all!

**Comment by Unkn09wn** [comment]
I've been trying to solve the above problem but I can not solve.

This is my code.

rl.question("Steam Guard Code: ", function(input) {

    var auth_code = SteamTotp.generateAuthCode(''),
        time = Math.floor(Date.now() / 1000),
        identity_secret = SteamTotp.getConfirmationKey(auth_code, time, 'conf'),
        totp = new TOTP(identity_secret);


    var accountInfo = {
        "accountName": steamBOT.username,
        "password": steamBOT.password,
        "steamguard": auth_code,
        "twoFactorCode": input,
    };

    community.login(accountInfo, function(err, sessionID, cookies, steamguard) {
        if(err) {
            console.log(err);
            return;
        }
        community.setCookies(cookies);

        manager.setCookies(cookies, function(err) {
            if(err) {
                console.log(err);
                return;
            }
            offers.setup({
                sessionID: sessionID,
                webCookie: cookies,
                APIKey: manager.apiKey
            });

            /** Initial Bot **/
            client.setPersona(SteamUser.Steam.EPersonaState.Online);
            logger.info("Cookies almacenadas correctamente!");
            logger.info("Detalles de sesión almacenadas correctamente!");
            logger.info("Steam API Key: "+manager.apiKey+"\n");
            logger.info("Servicio de comunicaciones bi-direccional establecido. (PORT: "+steamBOT.ws_port+")");
            app.listen(steamBOT.ws_port);
            logger.info("================[ESPERANDO OFERTAS]================");
            OnBotUpdate();

            // Example
            offers.loadMyInventory({
                appId: 730,
                contextId: '2'
            }, function(err, items) {
                logger.info("Enviando objeto de comisión!");
                offers.makeOffer({
                    partnerAccountId: '256122643',
                    accessToken: '1tq1bGm8',
                    itemsFromMe: [{
                        appid: 730,
                        contextid: '2',
                        amount: 1,
                        assetid: '4503270004'
                    }],
                    itemsFromThem: [{}],
                    message: '',
                }, function(err, response) {
                    if(err) {
                        logger.error(err);
                    }
                    else {
                        logger.info("El objeto de comisión ha sido enviado correctamente.");

                        community.getConfirmations(time, identity_secret, function(err, confirmations) {
                            if(err) return console.log(err);
                            console.log(confirmations);
                        });
                    }
                });
            });
        });
    });
});

**Comment by DoctorMcKay** [comment]
I assume that there's actually a secret between the `''` in `generateAuthCode('')`?

**Comment by Unkn09wn** [comment]
No, the result of this function gives me an alphanumeric code similar to the code Steam Guard. What should have been there?

**Comment by WeeSkilz** [comment]
@Unkn09wn please read the docs (https://github.com/DoctorMcKay/node-steam-totp) before asking questions.

The code I sent you on Discord relies on the other method that I sent you:

```function getConfirmationKey(tag) {
    return SteamTotp.getConfirmationKey('IDENTITY_SECRET', Math.floor(new Date().getTime() / 1000), tag);
}```

**Comment by scholtzm** [comment]
```js
    manager.setCookies(cookies, function(err) {
        if(err) {
            console.log(err);
            return;
        }
        offers.setup({
            sessionID: sessionID,
            webCookie: cookies,
            APIKey: manager.apiKey
        });
```

Why are you even using 2 different trade offer libs?
