### ISSUE TITLE
Loss Of Access

### ISSUE THREAD

**Issue by Milestacular** [DoctorMcKay/node-steamcommunity#48]
Is there a way to view the generated auth codes maybe in a real time log as I can no longer access my bot due to losing all access to mobile auth.

**Comment by DoctorMcKay** [comment]
I don't understand. 

If you lost your mobile authentication secrets, you're hosed and you'll need to reset it through the help site.

**Comment by Milestacular** [comment]
I have my secret ID etc just don't know how to get auth codes to login to other devices

**Comment by DoctorMcKay** [comment]
Use [`steam-totp`](https://www.npmjs.com/package/steam-totp).
