### ISSUE TITLE
getConfirmations returning empty.

### ISSUE THREAD

**Issue by dogmagames** [DoctorMcKay/node-steamcommunity#49]
When I call getConfirmations, i receive a callback with no errors, but the confirmations array is empty.
What Im doing it wrong?

**Comment by DoctorMcKay** [comment]
Either you have no confirmations, you're not logged in as the right user, or Steam is just being typical Steam.

**Comment by Ax6** [comment]
I'm having the same issue, empty confirmations array yet I'm making the offers correctly and getting a trade id, did you figure out what was wrong?

**Comment by dogmagames** [comment]
I figured out that you have to enable back in your Steam Profile Settings the 'trade confirmation by e-mail'.
