### ISSUE TITLE
Confirming sent trade offer

### ISSUE THREAD

**Issue by steamkid** [DoctorMcKay/node-steamcommunity#50]
Hi, so I'm almost finishing my code, I just need to solve the problem how to confirm trade offers.

My code looks:
```javascript
function checkConfirms() {
  
  time = Math.floor(Date.now() / 1000);
    key = SteamTotp.getConfirmationKey('IDENTITY', time, 'conf');
    console.log("Key: " + key);
    var offset, latency;
    var timez = Math.round(Date.now() / 1000);
  SteamTotp.getTimeOffset(function(err, response) {
 if( !err) {
    offset = response.offset;
    latency = response.latency;
    timez+=offset;
    timez+=latency/1000;
 }
  });
  community.getConfirmations(timez, key, function(err, confirmations) {
      if(err) return console.log(err);
      console.log("CONFIRMATIONS: " + confirmations);
  });
}

```

it works perfectly, i just need to accept all confirmations, how to do it?

**Comment by andrewda** [comment]
If you want to confirm all trades, take a look at the [`startConfirmationChecker()`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/Steam-Confirmation-Polling#startconfirmationcheckerpollinterval-identitysecret) and supply your identitySecret.

**Comment by DoctorMcKay** [comment]
As @andrewda said, `startConfirmationChecker` is probably your best bet.

One issue I noticed is that `response` isn't an object in `getTimeOffset`.

Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).
