### ISSUE TITLE
Error: This account is not authorized to use this feature. In getWebApiOauthToken()

### ISSUE THREAD

**Issue by StevePavlin** [DoctorMcKay/node-steamcommunity#52]
I have created a few accounts using your other library steam-user, yet when I try to activate 2fa with steam-community I get this error when my derivative of the example script calls enableTwoFactor()

I've tracked it down to the getWebApiOauthToken() which is called within enableTwoFactor() This seems to do a request to https://steamcommunity.com/chat and pulls an 'oauth' token from there needed to fulfill the 2fa request.

The problem is that, on a newly created account, even after email verification and purchasing a $5 US game, this URL seems to be inaccessible. My main account can access the url fine and I can see the token displayed in the HTML source.

https://i.gyazo.com/483167e00d58bda805e7715cff580107.png

This basically makes enabling a freshly created account to 2fa impossible. Would it be possible to change the way this method gets the oauth token?

**Comment by scholtzm** [comment]
1. Why don't you use 2FA methods in steam-user?
2. You could also use login function in steamcommunity and that should retrieve the OAuth token in the process.

**Comment by DoctorMcKay** [comment]
As @scholtzm said, you can either use node-steam-user or you can login directly through node-steamcommunity to get an oauth token that way. We don't know why web chat is being denied to accounts that should be able to access it. You'd need to ask Valve.

I'm updating the documentation to be a bit more clear about this.

Bottom line: If you're getting denied after using `setCookies`, you either need to call `login` directly from this module using your username/password/Steam Guard code, or you need to use node-steam-user's `enableTwoFactor`.
