### ISSUE TITLE
Error: Could not act on confirmation

### ISSUE THREAD

**Issue by Seebix** [DoctorMcKay/node-steamcommunity#58]
Hello. I am experiencing this type of error. I am using a function community.respondToConfirmation to accept a confirmation.

When I am trying to accept first offer, its going good. But when its trying to accept second offer after like 10 seconds its giving me that error. Using a ID and key from getConfirmations and parsing JSON. It gives correctly values. Tried also a thing which generates a new keys for allow after accepting/error. Still nothing, any ideas?

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/). 

Are you trying to reuse a confirmation key? Are you using the correct tag?

**Comment by Inkognitoo** [comment]
I have the same problem. 
May you help me? 
My code:

```
let time_conf = Math.floor(Date.now() / 1000);
        let key_conf = SteamTotp.getConfirmationKey(this.identity_secret, time_conf, "conf");
        this.community.getConfirmations(time_conf, key_conf, (err, confirmations) => {
            setTimeout(() => {
                let time = Math.floor(Date.now() / 1000);
                let key = SteamTotp.getConfirmationKey(this.identity_secret, time, "accept");
                confirmations[0].respond(time, key, true, function(err){
                    console.log('err', err);
                });
            }, 1001);
        });
```

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

Also, don't hijack. :)
