### ISSUE TITLE
Multiple bots with different IP addresses

### ISSUE THREAD

**Issue by jhartzell** [DoctorMcKay/node-steamcommunity#60]
Recently I've had a project crop up that requires us to spin up multiple instances of bots under different accounts. I am currently using version 3.14 of this library.

Whenever I attempt to assign a secondary IP address, technically an aliased address inside of ubuntu on a virtual adapter to the SteamCommunity() constructor it seems to login just fine, the bot comes online and everything "seems" to work. However upon receiving a request to send a trade offer it immediately errors out with 401 Unauthorized.

I am typically aware that this is an issue with cookies majority of the time and I should re-authenticate against steam to try and resolve this issue. Is this actually the issue or is there another issue specific to binding secondary IP's on the same box?

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/). 

I'm not aware of any trade offer issues related to secondary IPs.

**Comment by jhartzell** [comment]
Sorry! I'll be sure to post future questions there, one last thing. Is using the localAddress param in the constructor enough to handle all community/trade actions? Could it be the fact that I'm using the npm library 'steam-user'? 

I'm just a bit confused as I'm running these bots in child processes with specific IP's assigned to each CP that spawns up.

**Comment by DoctorMcKay** [comment]
Using `localAddress` in the constructor will ensure that all HTTP requests made by the module will use that IP. steam-user is another ball game. You'd need to use [`steam-client`](https://github.com/DoctorMcKay/node-steam-client) for that. Create a `CMClient`, [`bind`](https://github.com/DoctorMcKay/node-steam-client) it to a specific IP, and then pass that to `SteamUser`'s constructor.
