### ISSUE TITLE
Steam reports incorrect number of items in trade history

### ISSUE THREAD

**Issue by potato20** [DoctorMcKay/node-steamcommunity#62]
So, if your bot completes a trade with a user, but the trade is escrowed, and the user later cancels his escrowed trades, the inventory history of your bot will actually report the wrong number of items in the paging row

For example, in this screenshot

![image](https://cloud.githubusercontent.com/assets/15012117/12223374/7a0fe88c-b7a3-11e5-9fd7-ea170ea44582.png)

It only shows 3 items, but the top paging row reports `1-4 of 4` and the bottom reports `1-3 of 4`

This affects the `totalTrades` property of the returned object from `getInventoryHistory()`, so might I recommend simply counting the number of rows that have the class `tradehistoryrow` to get the value for that property? This probably affects some other things as well..

Would make a pr, but i'm preoccupied. might make one if i have time.

**Comment by DoctorMcKay** [comment]
Classic Steam. 

`totalTrades` is how many trades you have *total*, not how many are on this page. The only way to get a more accurate number would be to request all pages, which is out of the question. Unfortunately, we're just going to have to live with this.

**Comment by potato20** [comment]
Rofl alrighty

**Comment by scholtzm** [comment]
@DoctorMcKay From my experience surprisingly the widget you can put on your profile will display correct number of trades unlike the inventory history page.

**Comment by DoctorMcKay** [comment]
That's interesting, although we obviously can't very well require people to be level 10 and put that showcase on their profiles to use this method.

**Comment by potato20** [comment]
would be hilarious though

```
gotTotatlTrades(options, callback)
...
Requirements: Level 10 Steam account.
```
