### ISSUE TITLE
Error: You must fill out all fields in at least one language

### ISSUE THREAD

**Issue by TSDJ** [DoctorMcKay/node-steamcommunity#63]
when calling postAnnouncement it returns " Error: You must fill out all fields in at least one language
"

I have successfully logged in as a user that has privilege to post into the group

````javascript
group.postAnnouncement("Testing","This is a test",function(err){
    console.log(err);
});
````

**Comment by DoctorMcKay** [comment]
Fixed in [3.17.2](https://github.com/DoctorMcKay/node-steamcommunity/releases/tag/v3.17.2).
