### ISSUE TITLE
Enable 2FA Script

### ISSUE THREAD

**Issue by jeanggi90** [DoctorMcKay/node-steamcommunity#64]
I wrote a script which enables 2FA and save the response from the enableTwoFactor(callback) method in a site (it's very similar to your example script). I could manage to us the file to sign in in to my steam account in my botscript. But bizarrely I don't get an code on my smartphone. Is this normal when I activate 2FA with a script?

**Comment by andrewda** [comment]
Yes, you won't be able to get codes on your phone unless you input the keys into the files. Use this instead: http://scholtzm.github.io/steam-auth-web-util/

**Comment by jeanggi90** [comment]
Thank you for this quick and helpful response!
