### ISSUE TITLE
Can I be banned?

### ISSUE THREAD

**Issue by hrvasiliy** [DoctorMcKay/node-steamcommunity#66]
Hi! If I very often log in to steam can I be banned? For example every 10 seconds...

**Comment by andrewda** [comment]
I don't believe that you will be banned, but Steam may throttle your login requests or add a captcha.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).**

You can be throttled or captcha'd if you login very frequently, as @andrewda said.

**Comment by hrvasiliy** [comment]
@DoctorMcKay @andrewda Sorry, but how then to constantly send the trades? 1 time to run the bot and use a DB?

**Comment by DoctorMcKay** [comment]
Login once and use the same bot. I'm assuming you're using node.js, or else you're in the completely wrong place.
