### ISSUE TITLE
Problem with startConfirmationChecker

### ISSUE THREAD

**Issue by overheader** [DoctorMcKay/node-steamcommunity#67]
I have more than 200 trades per day.
5 per cent of them are not confirmed (the status of the trade == 9).
How to solve this problem and why they are not confirmed?

**Comment by scholtzm** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/issues/27

@DoctorMcKay Perhaps linking this in the Wiki wouldn't be a bad idea.

**Comment by DoctorMcKay** [comment]
Added a note to the confirmation polling wiki page.
