### ISSUE TITLE
could you provide me some code example?

### ISSUE THREAD

**Issue by nikadrenalin** [DoctorMcKay/node-steamcommunity#68]
I am developing a bot that automatically sends and receives proposals Could you share an example of code that will be very grateful

**Comment by LeCoffee** [comment]
By 'proposals' are you referring to TradeOffers or the Mobile confirmation things? If you're looking to do tradeoffers I'd recommend using:
https://github.com/DoctorMcKay/node-steam-user 
and
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager

There are examples in both of those libraries.

As for the mobile confirmations there is plenty of documentation in the wiki 
https://github.com/DoctorMcKay/node-steamcommunity/wiki
