### ISSUE TITLE
Problems trying to create Steam group events

### ISSUE THREAD

**Issue by ncronin** [DoctorMcKay/node-steamcommunity#7]
I'm trying to create a group event using the [Non-object method](https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamGroup#scheduleeventname-type-description-time-server-callback) but seem to be running into an issue.

Here is the snippet of code I'm using:
```javascript
steamCommunity.scheduleGroupEvent('103582791434160348', 'My Event!', '440', 'This is my Event!', null);
```

It throws this error upon trying to run:
https://gist.github.com/ncronin/c3e16a118342c97630a2

I may be using the snippet wrong, any help?

**Comment by DoctorMcKay** [comment]
Sorry about that, grab 3.9.8 and it should work.

**Comment by ncronin** [comment]
Sorry to re-open, no error is being thrown but no event is being made either. Could this possibly be because Steam Guard was recently auth'd?

**Comment by DoctorMcKay** [comment]
Are you sure that your account is logged in?

Since the method is asynchronous, errors won't be thrown. You'll need to add a callback to check for an error.

**Comment by ncronin** [comment]
It's definitely logged in as it's performing other tasks, I've tried as-is and an isolated test to no avail.

**Comment by DoctorMcKay** [comment]
>Since the method is asynchronous, errors won't be thrown. You'll need to add a callback to check for an error.

Find out what the error is.
