### ISSUE TITLE
[enhancement] Ability to invite users to a group? (Also accept / decline group invites?)

### ISSUE THREAD

**Issue by LeCoffee** [DoctorMcKay/node-steamcommunity#71]
I know this is a kind of touchy thing as it can easily result in plain spamming of invites however it is freely do-able via other modules now such as 

https://github.com/scholtzm/node-steam-groups

from @scholtzm who also monitors this repo apparently :+1:

I'd like to be able to do this via web instead of using steam-user and then using steam-groups and then rigging up some code to steam-groups to support steam-user since it was designed for node-steam etc etc.

I feel as though it would be pretty trivial however can be done through steam-community very easily although maybe better suited for steam-user. Or both, why not!

Possible feature? Yay? Nay?

**Comment by DoctorMcKay** [comment]
[It already exists.](https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamUser#invitetogroupgroupid-callback). There are also methods to join a group. 

Currently you can't get invites through steamcommunity as that would require HTML scraping and it can already be done with steam-user.

**Comment by scholtzm** [comment]
@LeCoffee There should be no need for rigging, it works with node-steam-user just fine. The only thing you need to do is pass [`client`](https://github.com/DoctorMcKay/node-steam-user#client) property to `steam-groups` constructor.

**Comment by LeCoffee** [comment]
Ah okay then steam groups never seemed to work out of the box for me with steam user that's all if it continues I'll clear my npm cache and such maybe I have an old version
