### ISSUE TITLE
Invalid protocol: steammobile:

### ISSUE THREAD

**Issue by inomushis** [DoctorMcKay/node-steamcommunity#72]
Hello everyone!
I'm using `community.getConfirmations()` to receive and accept mobile confirmations in interval.

```
function MobileConfirms(){
	community.getConfirmations( ... );
}

community.login(...{
if(!err){	
	MobileConfirms();
	setInterval(function(){
		if(_isSteamOK){
			MobileConfirms();
		}
	}, 60000);
} ...
});
```
This code works fine one-three hours. Next, MobileConfirms always return:
`Invalid protocol: steammobile:`

I tried to re-login (by community.login()) when error occurred, but it doesn't work.
Is any way to fix it? Currently only working method is to restart node.

Thank for your help!

**Comment by DoctorMcKay** [comment]
That's just Steam being Steam. You can't do anything except wait.
