### ISSUE TITLE
Endless debug: Accepting confirmation #Number

### ISSUE THREAD

**Issue by EduardChernikh** [DoctorMcKay/node-steamcommunity#74]
after setting cookies and startConfirmationChecker in my debug messages:

```javascript
community.on('debug', function(debugMessage) {
    console.log(debugMessage);
});
```

Can't check confirmations: Invalid protocol: steammobile:

I have these error. Can you help me. What is this?

**Comment by EduardChernikh** [comment]
And than these endless debug messages:

Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412
Communit debug: Checking confirmations
Communit debug: Accepting confirmation #73098412

**Comment by EduardChernikh** [comment]
He's not accepting any confirmations. Just sending messages...

**Comment by Aareksio** [comment]
#72

**Comment by DoctorMcKay** [comment]
Make sure you're logged in.
