### ISSUE TITLE
How i may use enableTwoFactor?

### ISSUE THREAD

**Issue by nikadrenalin** [DoctorMcKay/node-steamcommunity#78]
May i use this for automatic create TwoFactor for bot? Allow this register several bots on one telephone number end device? May i use this script in bot file or use for this separatli app?
Please help me stadyng this issue

**Comment by scholtzm** [comment]
Yes, to all of your questions.

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).

**Comment by nikadrenalin** [comment]
May i use this script in bot file or use for this separatli app?

**Comment by andrewda** [comment]
Don't put `enableTwoFactor` in your bot. You don't want to enable two factor authentication every time your bot restarts, do you? You should make a simple application that enables it once and gives you your keys, that's all you'll need.
