### ISSUE TITLE
Suggestion to add new feature for getting average price for an item

### ISSUE THREAD

**Issue by DavidBarishev** [DoctorMcKay/node-steamcommunity#8]
If this possible to be implemented , it would be nice to have a feature to get average price of a certain item over a 'n' piriod of time . Becuase I don't think there is much use for the get maden prices becuase the market isn't stable enough. 
Thanks!

**Comment by DoctorMcKay** [comment]
Steam only gives us median prices. You can calculate the average of those medians, but we can't get the raw averages.
