### ISSUE TITLE
Cannot get confirmations?

### ISSUE THREAD

**Issue by bagda391** [DoctorMcKay/node-steamcommunity#81]
Hi.

I am trying to do confirmation pooling but I get this error: 
https://gyazo.com/823dd55038d8ee4c3d412bd435a4c608

Can somebody tell me why?

Thanks.

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).

Are you logged in?

**Comment by bagda391** [comment]
Yes. Will post now
