### ISSUE TITLE
Captcha problem

### ISSUE THREAD

**Issue by merihdursun** [DoctorMcKay/node-steamcommunity#83]
https://steamcommunity.com/public/captcha.php?gid=844793180770331145

ITS my captcha url but nothing in the image. I cant read anything. How can i achieve this ?

**Comment by scholtzm** [comment]
I tried couple random `gid`s and they all return text-less captcha images. Seems like the issues is on their end. Not really related to this module anyway.

**Comment by Krash-ua** [comment]
Is it any solution for this? I have also discovered this bug about 5 days ago.

**Comment by andrewda** [comment]
I believe this is on Steam's end. Not really anything we can do about it.

**Comment by FelikZ** [comment]
@merihdursun Where do you face this captcha? Never face it personally.

**Comment by merihdursun** [comment]
when i try login it returns error CAPTCHA captchaid : link

**Comment by merihdursun** [comment]
anyone have an idea im still try to fix it
