### ISSUE TITLE
Question: Sentry usage from node-steam-user

### ISSUE THREAD

**Issue by Krash-ua** [DoctorMcKay/node-steamcommunity#84]
Could someone provide an example of logging in with sentry?
I am migrating from node-steam-user to node-steamcommunity but can\`t use sentry files from the first one. Also how should I store and use them with node-steamcommunity? Could you please provide an example? I haven\`t found it in examples. I have tried to simply use sentry like sentry:"F155690FF870A259E1911A0F1D3EBFB6291EB395" But it is not working. 
I have also tried to use sentry like this (deleted SteamID|| before writing in file)
```javascript
fs.writeFileSync(path.dirname(require.main.filename) + "/sentry", steamguard);
login.sentry = fs.readFileSync(path.dirname(require.main.filename) + "/sentry");

**Comment by scholtzm** [comment]
Afaik these 2 formats are not cross compatible.

**Comment by Krash-ua** [comment]
Oh, it is very dissapointing(( Could you please tell me how to write and use sentry with node-steamcommunity

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).**

I'm pretty sure that the examples in the examples directory save and reload sentries. The documentation also describes how to do so.

**Comment by Krash-ua** [comment]
I apologise for my unapprehensivness and asking not in the SteamGroup but could someone please tell me what is wrong with my login params and why do I get { [Error: SteamGuard] emaildomain: 'email.com' } instead of sessionId and cookies?
```javascript
 { accountName: 'name',
  password: 'password',
  sentry: '0DAD0E0DBC9BC55B6F8B5D4F9324F8F32B484037',
  steamID: { universe: 1, type: 1, instance: 1, accountid: 315793772 } }

```

**Comment by scholtzm** [comment]
[Check the docs again.](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#logindetails-callback)

**Comment by Krash-ua** [comment]
OMG, I was looking at SteamCommunity @ v1.0.x. Thank you!
