### ISSUE TITLE
getSteamUser getting exception

### ISSUE THREAD

**Issue by williamokano** [DoctorMcKay/node-steamcommunity#85]
Hi, I'm trying to user steamcommunity along with steam-user the get the username on the act the trading and when I call getSteamUser, passing a steamID object as parameter, I get an exception saying that the parameter should be a user URL or SteamID object.

I checked, the object type is correct, but somehow the comparison between id.__proto and SteamID.prototype is not matching.

Any ideas?

**PS.:**
console.log on the id (inside the method)
SteamID { universe: 1, type: 1, instance: 1, accountid: 84657490 }

console.log on the id.__proto__
SteamID {
  isValid: [Function],
  getSteam2RenderedID: [Function],
  getSteam3RenderedID: [Function],
  getSteamID64: [Function],
  toString: [Function] }

console.log on the SteamID.prototype
SteamID {
  isValid: [Function],
  getSteam2RenderedID: [Function],
  getSteam3RenderedID: [Function],
  getSteamID64: [Function],
  toString: [Function] }

**Comment by DoctorMcKay** [comment]
You have to use the `SteamID` available through `SteamCommunity.SteamID`. That's a less than ideal requirement and will be changing in the future though.
