### ISSUE TITLE
Example scripts should prompt for CAPTCHA solution if necessary

### ISSUE THREAD

**Issue by xenkocz** [DoctorMcKay/node-steamcommunity#88]
```
{ [Error: CAPTCHA]
  captchaurl: 'https://steamcommunity.com/login/rendercaptcha/?gid=858305155480192855' }
```

Hello, i got this error when i want enable_twofactor i'm using your example enable_twofactor.js
and i'm pretty lose now...

Gg...

**Comment by andrewda** [comment]
The captcha provided would be useless even if there was a prompt, because it renders an image with no text.

**Comment by DoctorMcKay** [comment]
That particular captcha has expired. It renders fine if it's fresh enough.

**Comment by andrewda** [comment]
Ah, alright. That makes sense.
