### ISSUE TITLE
Interesting Error on Confirmation Checker

### ISSUE THREAD

**Issue by centrual** [DoctorMcKay/node-steamcommunity#89]
Hello,

Thanks for this libraries dr. i can make bots faster than ever.

I trying to make multi account bot system, but when i start the confirmation checker this error happening:
`
node_modules\steam-totp\index.js:129
    at Object.exports.getDeviceID (C:\xampp\htdocs\GG\bot2\node_modules\steam-totp\index.js:129:62)
    at request (C:\xampp\htdocs\GG\bot2\node_modules\steamcommunity\components\confirmations.js:144:23)
    at SteamCommunity.getConfirmations (C:\xampp\htdocs\GG\bot2\node_modules\steamcommunity\components\confirmations.js:17:2)
    at C:\xampp\htdocs\GG\bot2\node_modules\steamcommunity\components\confirmations.js:240:8
    at SteamCommunity._confirmationCheckerGetKey (C:\xampp\htdocs\GG\bot2\node_modules\steamcommunity\components\confirmations.js:317:3)
    at SteamCommunity.checkConfirmations (C:\xampp\htdocs\GG\bot2\node_modules\s
teamcommunity\components\confirmations.js:234:7)
    at Timer.listOnTimeout (timers.js:92:15)
`

**My bot code's parts:**

`
function BotAccount( accData ) {
	
	var self = this;
	
	this.loginCompletedBefore = false;
	
	this.accountData 	= accData;
	this.loggedIn		= false;
	this.webSessionId	= "";
	this.webCookies		= "";
	this.accountLimits	= null;
	this.backpackItems	= 0;
	this.queueItems		= 0;
		
	this.community		= new steamCommunity();
	this.client			= new steamUser();
	
	var managerConf 	= {
		"steam"				: self.client,
		"domain"			: conf.site,
		"language"			: "en",
		"pollInterval"		: 2000,
		"cancelTime"		: 600000,
		"pendingCancelTime" : 30000
	};
	
	this.manager		= new tradeOffers(managerConf);
	
	// User Events
	this.onLoginCompleted = function() {};
	
	// Functions
	this.BindEvents = function() {
		self.manager.pollData = data.readPollData( self.accountData.USERNAME );
		self.client.dataDirectory = data.getDataDir();
		
		self.manager.on('pollData', self.onPollData);
		self.manager.on("sentOfferChanged", self.onSentOfferChanged);
		self.manager.on("pollFailure", self.onPollFailure);
		self.manager.on("pollSuccess", self.onPollSuccess);
		
		self.community.on("confKeyNeeded", self.onConfKeyNeeded);
		
		self.client.on('error', self.onClientError);
		self.client.on('debug', self.onClientDebugData);
		self.client.on('accountLimitations', self.onClientAccountLimitationsData);
		self.client.on('friendMessage', self.onClientFriendMessage);
		self.client.on('webSession', self.onNewSession);
		self.client.on('loggedOn', self.onLoggedOn);
		self.client.on('disconnected', self.onDisconnected);
	};
	
	this.Login = function() {
		
		self.BindEvents();
		
		var loginDetails = {
			accountName		: self.accountData.USERNAME,
			password		: self.accountData.PASSWORD,
			twoFactorCode	: totp.generateAuthCode(self.accountData.SHARED)
		};
		
		self.client.logOn(loginDetails);
	};

        this.onConfKeyNeeded = function(tag, callback) {
		console.log("Confirmation Key Needed. Tag:");
		console.log(tag);
		
		var time = helpers.time();
		callback(null, time, totp.getConfirmationKey(self.accountData.IDENTITY, time, tag));
	};

        this.onNewSession = function(sessionID, cookies) {
		self.webSessionId = sessionID;
		self.webCookies = cookies;
		
		if( self.loggedIn && self.accountLimits != null && typeof self.onLoginCompleted == "function" && !self.loginCompletedBefore )
		{
			self.loginCompletedBefore = true;
			self.onLoginCompleted(self);
		}
	};

	this.onClientAccountLimitationsData = function(limited, commBanned, locked, canInvFriends) {
		
		self.accountLimits = {
			"limited"			: limited,
			"communityBanned"	: commBanned,
			"locked"			: locked,
			"canInviteFriends"	: canInvFriends
		};
		
		console.log(self.accountData.USERNAME + " Limitations:");
		console.log(self.accountLimits);
		
		if( self.loggedIn && self.webSessionId != "" && self.webCookies != "" && typeof self.onLoginCompleted == "function" && !self.loginCompletedBefore )
		{
			self.loginCompletedBefore = true;
			self.onLoginCompleted(self);
		}
	};

	this.onLoggedOn = function(details) {
		self.loggedIn = true;
	};
	
	this.onDisconnected = function(details) {
		self.loggedIn		= false;
		self.webSessionId	= null;
		self.webCookies		= null;
		self.accountLimits	= null;
	};
}
`

After that, when all bots logged in i calling this:
`
      system.bots.forEach( function( bot ) {
            bot.community.startConfirmationChecker(3000, bot.accountData.IDENTITY);
      });
`

I know %90 chance it's my fault, but if you can, can you help me for fix it?

**Comment by DoctorMcKay** [comment]
Somehow you left out the actual error message, but it's very likely that you're trying to start the checker before you're actually logged in.
