### ISSUE TITLE
getSteamUser does not work with foreign SteamID's

### ISSUE THREAD

**Issue by andrich48** [DoctorMcKay/node-steamcommunity#90]
node-steamcommunity, node-steam-user, node-steam-tradeoffer-manager, they all use 'steamid' package for internal procedures. But when I try to get 'SteamID' object from node-steam-user package and use getSteamUser method from node-steamcommunity package, it crashes with error.
```javascript
var community = new SteamCommunity();
var client = new SteamUser();
(...)
client.on('loggedOn', function (details) {
    community.getSteamUser(client.steamID,function(err,user) { true; });
});
```
error:
```javascript
/node_modules/steamcommunity/classes/CSteamUser.js:7
                throw new Error("id parameter should be a user URL string or a SteamID object");
Error: id parameter should be a user URL string or a SteamID object
```
What am I doing wrong? How to make it work?
My aim is to use node-steam-tradeoffer-manager, extract SteamID from incoming offers, and then use node-steamcommunity to get various information about users.

**Comment by DoctorMcKay** [comment]
You aren't doing anything wrong. This is a bug in the package. I'll see about fixing it tonight.

**Comment by andrich48** [comment]
Thanks a lot for fast reply and fixing! Now everything works fine.

**Comment by DoctorMcKay** [comment]
:)
