### ISSUE TITLE
Classid of CEonItem

### ISSUE THREAD

**Issue by SzymonLisowiec** [DoctorMcKay/node-steamcommunity#91]
Hello,
Classid is unique on all steam items or one game items?

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**
