### ISSUE TITLE
Add `sessionExpiried` event to the wiki

### ISSUE THREAD

**Issue by Aareksio** [DoctorMcKay/node-steamcommunity#92]
Add the event `sessionExpiried` featured in 1884ceb7d99dc26fb40821e2bf88ce00c3006d7b and mentioned in DoctorMcKay/node-steam-tradeoffer-manager#28 earlier today to the wiki, it may be quite useful :+1:

**Comment by DoctorMcKay** [comment]
Done: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#sessionexpired
