### ISSUE TITLE
Login with 2FA ?

### ISSUE THREAD

**Issue by MaxYari** [DoctorMcKay/node-steamcommunity#95]
Hello there, as far as I understand after implementation of escrow any bot system relying on trade offer must use 2 factor authentication with confirmation code generation usually done on bot's side (steam-bot does it like this afaik) to confirm each trade automatically. So, i can see methods to bind 2FA in node-steamcommunity, but i don't see a way to generate a code and use it to login. So is it currently supported?

Reason behind it is that I wanted to use node-steamcommunity with node-steam-tradeoffers to build simple trade offers bot.

**Comment by MaxYari** [comment]
Oh sorry i suppose i just missed a point of some functions in docs, now i get it more or less, so there is respondToConfirmation, but where should i get confID and confKey for it?

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue_. GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

**Comment by MaxYari** [comment]
Got it, pardon me for that.
