### ISSUE TITLE
enable_twofactor.js do not getting SMS

### ISSUE THREAD

**Issue by tambu22** [DoctorMcKay/node-steamcommunity#97]
First of all can u add a method to atach the phone number from code? 
second: i atach the number manually from steam, and then when i try to add mobile auth with this code i do not resive the SMS to confirm it  :/

**Comment by DoctorMcKay** [comment]
1. https://github.com/DoctorMcKay/node-steamstore#addphonenumbernumber-bypassconfirmation-callback
2. Worked for me the other day. You're either doing something wrong or Steam doesn't like your number.
