### ISSUE TITLE
i can't even getting login :d

### ISSUE THREAD

**Issue by AKagNA** [DoctorMcKay/node-steamcommunity#99]
Guys i have a code like that

`var TradeOfferManager = require('steam-tradeoffer-manager')
var SteamCommunity = require('steamcommunity')
var fs = require('fs')
var SteamTotp = require('steam-totp')

// AuthCode Ayarları

//var code = SteamTotp.generateAuthCode('kk')

// Giriş

var community = new SteamCommunity();

community.login({
	accountName: "mabotid",
	password: "mabotpas"
}, function(err, sessionID, cookies, captcha) {
	if(err) {
		console.log(err + "Sikinti var baskan")
	}
	else {
		console.log("Giris yaptik")
	}
});

community.loggedIn(function(err, loggedIn) {
	if(err){
		console.log(err)
	}
	else {
		console.log(loggedIn)
	}
});

// web api

var domain = "steamcommunity.com/id/trieeedtradebot/";

community.getWebApiKey(domain, function(err, key) {
	if(err) {
		console.log(err)
	}
	else {
		console.log(key)
	}
});

//

community.getSessionID();

community.editProfile({
	name: "ehhueuhueuhe",
});

community.profileSettings({
	profile: 3,
	comments: 1,
	inventory: 3
});

// Trade Ayarları

var offer = new TradeOfferManager();`

And thats giving me,

```
false
[error: not logged in]
Giris yaptik
```

What i'm doing wrong?

**Comment by AKagNA** [comment]
Sorry, i was not know there is not question part. Only bugs and future ideas. Sorry, but when you are closing the thread, can you answer? Pls.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/).**

You aren't logged in until the callback to login fires, but you're trying to do stuff before that. [This tutorial on callbacks might help.](http://cwbuecheler.com/web/tutorials/2013/javascript-callbacks/)
